[2025-04-29T06:45:10.918+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-04-29T06:45:15.254+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: random_user_pipeline.insert_postgres scheduled__2025-04-28T18:00:58+00:00 [queued]>
[2025-04-29T06:45:15.303+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: random_user_pipeline.insert_postgres scheduled__2025-04-28T18:00:58+00:00 [queued]>
[2025-04-29T06:45:15.305+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-04-29T06:45:15.415+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): insert_postgres> on 2025-04-28 18:00:58+00:00
[2025-04-29T06:45:15.435+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'random_user_pipeline', 'insert_***', 'scheduled__2025-04-28T18:00:58+00:00', '--job-id', '121', '--raw', '--subdir', 'DAGS_FOLDER/random_user_pipeline.py', '--cfg-path', '/tmp/tmpa4mpjl8b']
[2025-04-29T06:45:15.445+0000] {standard_task_runner.py:91} INFO - Job 121: Subtask insert_***
[2025-04-29T06:45:15.469+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=254) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-04-29T06:45:15.471+0000] {standard_task_runner.py:63} INFO - Started process 266 to run task
[2025-04-29T06:45:31.235+0000] {task_command.py:426} INFO - Running <TaskInstance: random_user_pipeline.insert_postgres scheduled__2025-04-28T18:00:58+00:00 [running]> on host 04b4fc26656e
[2025-04-29T06:55:36.531+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='random_user_pipeline' AIRFLOW_CTX_TASK_ID='insert_***' AIRFLOW_CTX_EXECUTION_DATE='2025-04-28T18:00:58+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-28T18:00:58+00:00'
[2025-04-29T06:55:36.533+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-04-29T06:55:36.588+0000] {logging_mixin.py:188} INFO - Fetched Product Data: N
[2025-04-29T06:55:43.352+0000] {logging_mixin.py:188} INFO - Database connection established.
[2025-04-29T06:55:43.358+0000] {logging_mixin.py:188} INFO - Table creation or existence check passed.
[2025-04-29T06:55:43.359+0000] {logging_mixin.py:188} INFO - Error during database operation: string indices must be integers, not 'str'
[2025-04-29T06:55:43.362+0000] {logging_mixin.py:188} INFO - Database connection closed.
[2025-04-29T06:55:43.363+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-04-29T06:55:43.364+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/storage/postgres_loader/write_to_postgres.py", line 67, in write_to_postgres
    raise e
  File "/opt/airflow/dags/storage/postgres_loader/write_to_postgres.py", line 50, in write_to_postgres
    product['name'],
    ~~~~~~~^^^^^^^^
TypeError: string indices must be integers, not 'str'
[2025-04-29T06:55:50.498+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=random_user_pipeline, task_id=insert_***, run_id=scheduled__2025-04-28T18:00:58+00:00, execution_date=20250428T180058, start_date=20250429T064515, end_date=20250429T065550
[2025-04-29T06:55:50.577+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 121 for task insert_*** (string indices must be integers, not 'str'; 266)
[2025-04-29T06:55:55.956+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-04-29T06:55:58.199+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-29T06:55:58.213+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
