[2025-04-28T16:14:05.917+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-04-28T16:14:08.455+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: random_user_pipeline.insert_postgres scheduled__2025-04-28T16:00:01+00:00 [queued]>
[2025-04-28T16:14:08.473+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: random_user_pipeline.insert_postgres scheduled__2025-04-28T16:00:01+00:00 [queued]>
[2025-04-28T16:14:08.475+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2025-04-28T16:14:08.502+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): insert_postgres> on 2025-04-28 16:00:01+00:00
[2025-04-28T16:14:08.511+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'random_user_pipeline', 'insert_***', 'scheduled__2025-04-28T16:00:01+00:00', '--job-id', '74', '--raw', '--subdir', 'DAGS_FOLDER/random_user_pipeline.py', '--cfg-path', '/tmp/tmp0aw2wjva']
[2025-04-28T16:14:08.515+0000] {standard_task_runner.py:91} INFO - Job 74: Subtask insert_***
[2025-04-28T16:14:08.519+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=218) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-04-28T16:14:08.521+0000] {standard_task_runner.py:63} INFO - Started process 237 to run task
[2025-04-28T16:14:15.017+0000] {task_command.py:426} INFO - Running <TaskInstance: random_user_pipeline.insert_postgres scheduled__2025-04-28T16:00:01+00:00 [running]> on host c6abaffabc50
[2025-04-28T16:14:32.637+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='random_user_pipeline' AIRFLOW_CTX_TASK_ID='insert_***' AIRFLOW_CTX_EXECUTION_DATE='2025-04-28T16:00:01+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-28T16:00:01+00:00'
[2025-04-28T16:14:32.639+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-04-28T16:14:32.655+0000] {logging_mixin.py:188} INFO - Fetched Product Data: N
[2025-04-28T16:14:36.379+0000] {logging_mixin.py:188} INFO - Database connection established.
[2025-04-28T16:14:36.383+0000] {logging_mixin.py:188} INFO - Table creation or existence check passed.
[2025-04-28T16:14:36.383+0000] {logging_mixin.py:188} INFO - Error inserting data into PostgreSQL: string indices must be integers, not 'str'
[2025-04-28T16:14:36.384+0000] {logging_mixin.py:188} INFO - Connection closed.
[2025-04-28T16:14:36.384+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-04-28T16:14:36.385+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/storage/postgres_loader/write_to_postgres.py", line 75, in write_to_postgres
    raise e
  File "/opt/airflow/dags/storage/postgres_loader/write_to_postgres.py", line 60, in write_to_postgres
    product['name'],
    ~~~~~~~^^^^^^^^
TypeError: string indices must be integers, not 'str'
[2025-04-28T16:14:39.377+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=random_user_pipeline, task_id=insert_***, run_id=scheduled__2025-04-28T16:00:01+00:00, execution_date=20250428T160001, start_date=20250428T161408, end_date=20250428T161439
[2025-04-28T16:14:39.402+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 74 for task insert_*** (string indices must be integers, not 'str'; 237)
[2025-04-28T16:14:42.933+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-04-28T16:14:44.714+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-28T16:14:44.718+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
