[2025-04-29T14:28:37.593+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-04-29T14:28:38.159+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: random_user_pipeline.insert_postgres scheduled__2025-04-29T14:00:58+00:00 [queued]>
[2025-04-29T14:28:38.205+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: random_user_pipeline.insert_postgres scheduled__2025-04-29T14:00:58+00:00 [queued]>
[2025-04-29T14:28:38.206+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2025-04-29T14:28:38.257+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): insert_postgres> on 2025-04-29 14:00:58+00:00
[2025-04-29T14:28:38.268+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'random_user_pipeline', 'insert_***', 'scheduled__2025-04-29T14:00:58+00:00', '--job-id', '131', '--raw', '--subdir', 'DAGS_FOLDER/random_user_pipeline.py', '--cfg-path', '/tmp/tmpzvjvd7hy']
[2025-04-29T14:28:38.273+0000] {standard_task_runner.py:91} INFO - Job 131: Subtask insert_***
[2025-04-29T14:28:38.277+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=253) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-04-29T14:28:38.278+0000] {standard_task_runner.py:63} INFO - Started process 254 to run task
[2025-04-29T14:28:39.684+0000] {task_command.py:426} INFO - Running <TaskInstance: random_user_pipeline.insert_postgres scheduled__2025-04-29T14:00:58+00:00 [running]> on host 4f4a27253082
[2025-04-29T14:28:42.303+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='random_user_pipeline' AIRFLOW_CTX_TASK_ID='insert_***' AIRFLOW_CTX_EXECUTION_DATE='2025-04-29T14:00:58+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-29T14:00:58+00:00'
[2025-04-29T14:28:42.305+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-04-29T14:28:42.329+0000] {logging_mixin.py:188} INFO - Fetched Product Data: N
[2025-04-29T14:28:42.730+0000] {logging_mixin.py:188} INFO - Database connection established.
[2025-04-29T14:28:42.735+0000] {logging_mixin.py:188} INFO - Table creation or existence check passed.
[2025-04-29T14:28:42.736+0000] {logging_mixin.py:188} INFO - Error during database operation: string indices must be integers, not 'str'
[2025-04-29T14:28:42.739+0000] {logging_mixin.py:188} INFO - Database connection closed.
[2025-04-29T14:28:42.740+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-04-29T14:28:42.741+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/storage/postgres_loader/write_to_postgres.py", line 67, in write_to_postgres
    raise e
  File "/opt/airflow/dags/storage/postgres_loader/write_to_postgres.py", line 50, in write_to_postgres
    product['name'],
    ~~~~~~~^^^^^^^^
TypeError: string indices must be integers, not 'str'
[2025-04-29T14:28:43.155+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=random_user_pipeline, task_id=insert_***, run_id=scheduled__2025-04-29T14:00:58+00:00, execution_date=20250429T140058, start_date=20250429T142838, end_date=20250429T142843
[2025-04-29T14:28:43.195+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 131 for task insert_*** (string indices must be integers, not 'str'; 254)
[2025-04-29T14:28:43.207+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-04-29T14:28:43.841+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-29T14:28:43.845+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
