[2025-04-28T15:51:19.837+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-04-28T15:51:20.150+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: random_user_pipeline.insert_postgres scheduled__2025-04-28T15:30:58+00:00 [queued]>
[2025-04-28T15:51:20.171+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: random_user_pipeline.insert_postgres scheduled__2025-04-28T15:30:58+00:00 [queued]>
[2025-04-28T15:51:20.172+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-04-28T15:51:20.195+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): insert_postgres> on 2025-04-28 15:30:58+00:00
[2025-04-28T15:51:20.203+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'random_user_pipeline', 'insert_***', 'scheduled__2025-04-28T15:30:58+00:00', '--job-id', '17', '--raw', '--subdir', 'DAGS_FOLDER/random_user_pipeline.py', '--cfg-path', '/tmp/tmpcagcnevg']
[2025-04-28T15:51:20.206+0000] {standard_task_runner.py:91} INFO - Job 17: Subtask insert_***
[2025-04-28T15:51:20.210+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=180) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-04-28T15:51:20.212+0000] {standard_task_runner.py:63} INFO - Started process 188 to run task
[2025-04-28T15:51:20.919+0000] {task_command.py:426} INFO - Running <TaskInstance: random_user_pipeline.insert_postgres scheduled__2025-04-28T15:30:58+00:00 [running]> on host 3d30dcd1551a
[2025-04-28T15:51:22.083+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='random_user_pipeline' AIRFLOW_CTX_TASK_ID='insert_***' AIRFLOW_CTX_EXECUTION_DATE='2025-04-28T15:30:58+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-28T15:30:58+00:00'
[2025-04-28T15:51:22.084+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-04-28T15:51:22.096+0000] {logging_mixin.py:188} INFO - No valid product data found in the response.
[2025-04-28T15:51:22.097+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-04-28T15:51:22.097+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-04-28T15:51:22.308+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=random_user_pipeline, task_id=insert_***, run_id=scheduled__2025-04-28T15:30:58+00:00, execution_date=20250428T153058, start_date=20250428T155120, end_date=20250428T155122
[2025-04-28T15:51:22.356+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-04-28T15:51:22.660+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-28T15:51:22.663+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
