[2025-04-28T15:55:52.534+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-04-28T15:55:52.832+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: random_user_pipeline.insert_postgres manual__2025-04-28T15:55:45.685955+00:00 [queued]>
[2025-04-28T15:55:52.848+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: random_user_pipeline.insert_postgres manual__2025-04-28T15:55:45.685955+00:00 [queued]>
[2025-04-28T15:55:52.850+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-04-28T15:55:52.872+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): insert_postgres> on 2025-04-28 15:55:45.685955+00:00
[2025-04-28T15:55:52.879+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'random_user_pipeline', 'insert_***', 'manual__2025-04-28T15:55:45.685955+00:00', '--job-id', '21', '--raw', '--subdir', 'DAGS_FOLDER/random_user_pipeline.py', '--cfg-path', '/tmp/tmpl9_v5ygy']
[2025-04-28T15:55:52.881+0000] {standard_task_runner.py:91} INFO - Job 21: Subtask insert_***
[2025-04-28T15:55:52.883+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=247) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-04-28T15:55:52.884+0000] {standard_task_runner.py:63} INFO - Started process 248 to run task
[2025-04-28T15:55:53.667+0000] {task_command.py:426} INFO - Running <TaskInstance: random_user_pipeline.insert_postgres manual__2025-04-28T15:55:45.685955+00:00 [running]> on host 3d30dcd1551a
[2025-04-28T15:55:55.097+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='random_user_pipeline' AIRFLOW_CTX_TASK_ID='insert_***' AIRFLOW_CTX_EXECUTION_DATE='2025-04-28T15:55:45.685955+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-28T15:55:45.685955+00:00'
[2025-04-28T15:55:55.098+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-04-28T15:55:55.111+0000] {logging_mixin.py:188} INFO - No valid product data found in the response.
[2025-04-28T15:55:55.112+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-04-28T15:55:55.112+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-04-28T15:55:55.299+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=random_user_pipeline, task_id=insert_***, run_id=manual__2025-04-28T15:55:45.685955+00:00, execution_date=20250428T155545, start_date=20250428T155552, end_date=20250428T155555
[2025-04-28T15:55:55.352+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-04-28T15:55:55.613+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-28T15:55:55.617+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
