[2025-05-24T03:24:14.266+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-05-24T03:24:14.807+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: random_user_pipeline.wait_for_existing_data manual__2025-05-24T03:24:10.714665+00:00 [queued]>
[2025-05-24T03:24:14.836+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: random_user_pipeline.wait_for_existing_data manual__2025-05-24T03:24:10.714665+00:00 [queued]>
[2025-05-24T03:24:14.838+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-05-24T03:24:14.909+0000] {taskinstance.py:2330} INFO - Executing <Task(SqlSensor): wait_for_existing_data> on 2025-05-24 03:24:10.714665+00:00
[2025-05-24T03:24:14.928+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=231) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-05-24T03:24:14.926+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'random_user_pipeline', 'wait_for_existing_data', 'manual__2025-05-24T03:24:10.714665+00:00', '--job-id', '443', '--raw', '--subdir', 'DAGS_FOLDER/random_user_pipeline.py', '--cfg-path', '/tmp/tmpmryikw_m']
[2025-05-24T03:24:14.930+0000] {standard_task_runner.py:63} INFO - Started process 232 to run task
[2025-05-24T03:24:14.931+0000] {standard_task_runner.py:91} INFO - Job 443: Subtask wait_for_existing_data
[2025-05-24T03:24:16.437+0000] {task_command.py:426} INFO - Running <TaskInstance: random_user_pipeline.wait_for_existing_data manual__2025-05-24T03:24:10.714665+00:00 [running]> on host fed8e0f764cf
[2025-05-24T03:24:18.421+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='papala.ramesh@quation.in,smilesoframs@gmail.com,ramesh.rams333@gmail.com' AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='random_user_pipeline' AIRFLOW_CTX_TASK_ID='wait_for_existing_data' AIRFLOW_CTX_EXECUTION_DATE='2025-05-24T03:24:10.714665+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-24T03:24:10.714665+00:00'
[2025-05-24T03:24:18.423+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-05-24T03:24:18.453+0000] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2025-05-24T03:24:18.454+0000] {base.py:84} INFO - Using connection ID '***_default' for task execution.
[2025-05-24T03:24:18.458+0000] {sql.py:95} INFO - Poking: SELECT 1 FROM products WHERE DATE(created_at) = CURRENT_DATE LIMIT 1; (with parameters None)
[2025-05-24T03:24:18.461+0000] {base.py:84} INFO - Using connection ID '***_default' for task execution.
[2025-05-24T03:24:18.867+0000] {sql.py:487} INFO - Running statement: SELECT 1 FROM products WHERE DATE(created_at) = CURRENT_DATE LIMIT 1;, parameters: None
[2025-05-24T03:24:18.875+0000] {sql.py:496} INFO - Rows affected: 0
[2025-05-24T03:24:48.876+0000] {base.py:84} INFO - Using connection ID '***_default' for task execution.
[2025-05-24T03:24:48.877+0000] {sql.py:95} INFO - Poking: SELECT 1 FROM products WHERE DATE(created_at) = CURRENT_DATE LIMIT 1; (with parameters None)
[2025-05-24T03:24:48.877+0000] {base.py:84} INFO - Using connection ID '***_default' for task execution.
[2025-05-24T03:24:49.317+0000] {sql.py:487} INFO - Running statement: SELECT 1 FROM products WHERE DATE(created_at) = CURRENT_DATE LIMIT 1;, parameters: None
[2025-05-24T03:24:49.325+0000] {sql.py:496} INFO - Rows affected: 0
[2025-05-24T03:25:19.329+0000] {base.py:84} INFO - Using connection ID '***_default' for task execution.
[2025-05-24T03:25:19.329+0000] {sql.py:95} INFO - Poking: SELECT 1 FROM products WHERE DATE(created_at) = CURRENT_DATE LIMIT 1; (with parameters None)
[2025-05-24T03:25:19.330+0000] {base.py:84} INFO - Using connection ID '***_default' for task execution.
[2025-05-24T03:25:19.772+0000] {sql.py:487} INFO - Running statement: SELECT 1 FROM products WHERE DATE(created_at) = CURRENT_DATE LIMIT 1;, parameters: None
[2025-05-24T03:25:19.780+0000] {sql.py:496} INFO - Rows affected: 0
[2025-05-24T03:25:49.781+0000] {base.py:84} INFO - Using connection ID '***_default' for task execution.
[2025-05-24T03:25:49.783+0000] {sql.py:95} INFO - Poking: SELECT 1 FROM products WHERE DATE(created_at) = CURRENT_DATE LIMIT 1; (with parameters None)
[2025-05-24T03:25:49.785+0000] {base.py:84} INFO - Using connection ID '***_default' for task execution.
[2025-05-24T03:25:50.227+0000] {sql.py:487} INFO - Running statement: SELECT 1 FROM products WHERE DATE(created_at) = CURRENT_DATE LIMIT 1;, parameters: None
[2025-05-24T03:25:50.234+0000] {sql.py:496} INFO - Rows affected: 0
[2025-05-24T03:26:20.236+0000] {base.py:84} INFO - Using connection ID '***_default' for task execution.
[2025-05-24T03:26:20.238+0000] {sql.py:95} INFO - Poking: SELECT 1 FROM products WHERE DATE(created_at) = CURRENT_DATE LIMIT 1; (with parameters None)
[2025-05-24T03:26:20.239+0000] {base.py:84} INFO - Using connection ID '***_default' for task execution.
[2025-05-24T03:26:20.629+0000] {sql.py:487} INFO - Running statement: SELECT 1 FROM products WHERE DATE(created_at) = CURRENT_DATE LIMIT 1;, parameters: None
[2025-05-24T03:26:20.635+0000] {sql.py:496} INFO - Rows affected: 0
[2025-05-24T03:26:20.638+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-05-24T03:26:20.639+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/sensors/base.py", line 281, in execute
    raise AirflowSensorTimeout(message)
airflow.exceptions.AirflowSensorTimeout: Sensor has timed out; run duration of 122.19721914301044 seconds exceeds the specified timeout of 120.0.
[2025-05-24T03:26:21.090+0000] {taskinstance.py:1206} INFO - Immediate failure requested. Marking task as FAILED. dag_id=random_user_pipeline, task_id=wait_for_existing_data, run_id=manual__2025-05-24T03:24:10.714665+00:00, execution_date=20250524T032410, start_date=20250524T032414, end_date=20250524T032621
[2025-05-24T03:26:21.132+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/utils/email.py:154 RemovedInAirflow3Warning: Fetching SMTP credentials from configuration variables will be deprecated in a future release. Please set credentials using a connection instead.
[2025-05-24T03:26:21.133+0000] {email.py:271} INFO - Email alerting: attempt 1
[2025-05-24T03:26:22.857+0000] {email.py:282} INFO - Sent an alert email to ['papala.ramesh@quation.in', 'smilesoframs@gmail.com', 'ramesh.rams333@gmail.com']
[2025-05-24T03:26:26.186+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 443 for task wait_for_existing_data (Sensor has timed out; run duration of 122.19721914301044 seconds exceeds the specified timeout of 120.0.; 232)
[2025-05-24T03:26:26.218+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-05-24T03:26:26.668+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py:1297 AirflowProviderDeprecationWarning: Call to deprecated class PostgresOperator. (Please use `airflow.providers.common.sql.operators.sql.SQLExecuteQueryOperator`.Also, you can provide `hook_params={'schema': <database>}`.)
[2025-05-24T03:26:26.708+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-05-24T03:26:26.720+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
