[2025-05-22T04:36:48.294+0000] {processor.py:161} INFO - Started process (PID=2799) to work on /opt/airflow/dags/(niu)operators.py
[2025-05-22T04:36:48.295+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/(niu)operators.py for tasks to queue
[2025-05-22T04:36:48.296+0000] {logging_mixin.py:188} INFO - [2025-05-22T04:36:48.295+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/(niu)operators.py
[2025-05-22T04:36:48.312+0000] {logging_mixin.py:188} INFO - [2025-05-22T04:36:48.311+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/(niu)operators.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/(niu)operators.py", line 32
    Operator (Tasks)
    ^^^^^^^^
IndentationError: expected an indented block after 'with' statement on line 22
[2025-05-22T04:36:48.313+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/(niu)operators.py
[2025-05-22T04:36:48.541+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/(niu)operators.py took 0.251 seconds
[2025-05-22T04:37:19.275+0000] {processor.py:161} INFO - Started process (PID=2814) to work on /opt/airflow/dags/(niu)operators.py
[2025-05-22T04:37:19.276+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/(niu)operators.py for tasks to queue
[2025-05-22T04:37:19.277+0000] {logging_mixin.py:188} INFO - [2025-05-22T04:37:19.277+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/(niu)operators.py
[2025-05-22T04:37:19.296+0000] {logging_mixin.py:188} INFO - [2025-05-22T04:37:19.295+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/(niu)operators.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/(niu)operators.py", line 32
    Operator (Tasks)
    ^^^^^^^^
IndentationError: expected an indented block after 'with' statement on line 22
[2025-05-22T04:37:19.297+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/(niu)operators.py
[2025-05-22T04:37:19.514+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/(niu)operators.py took 0.245 seconds
[2025-05-22T04:37:50.046+0000] {processor.py:161} INFO - Started process (PID=2829) to work on /opt/airflow/dags/(niu)operators.py
[2025-05-22T04:37:50.047+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/(niu)operators.py for tasks to queue
[2025-05-22T04:37:50.048+0000] {logging_mixin.py:188} INFO - [2025-05-22T04:37:50.048+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/(niu)operators.py
[2025-05-22T04:37:50.065+0000] {logging_mixin.py:188} INFO - [2025-05-22T04:37:50.064+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/(niu)operators.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/(niu)operators.py", line 32
    Operator (Tasks)
    ^^^^^^^^
IndentationError: expected an indented block after 'with' statement on line 22
[2025-05-22T04:37:50.066+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/(niu)operators.py
[2025-05-22T04:37:50.292+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/(niu)operators.py took 0.251 seconds
[2025-05-22T04:38:20.997+0000] {processor.py:161} INFO - Started process (PID=2844) to work on /opt/airflow/dags/(niu)operators.py
[2025-05-22T04:38:20.997+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/(niu)operators.py for tasks to queue
[2025-05-22T04:38:20.998+0000] {logging_mixin.py:188} INFO - [2025-05-22T04:38:20.998+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/(niu)operators.py
[2025-05-22T04:38:21.010+0000] {logging_mixin.py:188} INFO - [2025-05-22T04:38:21.009+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/(niu)operators.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/(niu)operators.py", line 32
    Operator (Tasks)
    ^^^^^^^^
IndentationError: expected an indented block after 'with' statement on line 22
[2025-05-22T04:38:21.011+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/(niu)operators.py
[2025-05-22T04:38:21.249+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/(niu)operators.py took 0.257 seconds
[2025-05-22T04:38:51.841+0000] {processor.py:161} INFO - Started process (PID=2859) to work on /opt/airflow/dags/(niu)operators.py
[2025-05-22T04:38:51.842+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/(niu)operators.py for tasks to queue
[2025-05-22T04:38:51.843+0000] {logging_mixin.py:188} INFO - [2025-05-22T04:38:51.843+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/(niu)operators.py
[2025-05-22T04:38:51.862+0000] {logging_mixin.py:188} INFO - [2025-05-22T04:38:51.861+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/(niu)operators.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/(niu)operators.py", line 32
    Operator (Tasks)
    ^^^^^^^^
IndentationError: expected an indented block after 'with' statement on line 22
[2025-05-22T04:38:51.863+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/(niu)operators.py
[2025-05-22T04:38:54.109+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/(niu)operators.py took 2.273 seconds
[2025-05-22T04:39:24.655+0000] {processor.py:161} INFO - Started process (PID=2874) to work on /opt/airflow/dags/(niu)operators.py
[2025-05-22T04:39:24.656+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/(niu)operators.py for tasks to queue
[2025-05-22T04:39:24.657+0000] {logging_mixin.py:188} INFO - [2025-05-22T04:39:24.656+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/(niu)operators.py
[2025-05-22T04:39:24.669+0000] {logging_mixin.py:188} INFO - [2025-05-22T04:39:24.668+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/(niu)operators.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/(niu)operators.py", line 32
    Operator (Tasks)
    ^^^^^^^^
IndentationError: expected an indented block after 'with' statement on line 22
[2025-05-22T04:39:24.669+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/(niu)operators.py
[2025-05-22T04:39:24.926+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/(niu)operators.py took 0.276 seconds
[2025-05-22T04:39:55.544+0000] {processor.py:161} INFO - Started process (PID=2889) to work on /opt/airflow/dags/(niu)operators.py
[2025-05-22T04:39:55.544+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/(niu)operators.py for tasks to queue
[2025-05-22T04:39:55.545+0000] {logging_mixin.py:188} INFO - [2025-05-22T04:39:55.545+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/(niu)operators.py
[2025-05-22T04:39:55.559+0000] {logging_mixin.py:188} INFO - [2025-05-22T04:39:55.558+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/(niu)operators.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/(niu)operators.py", line 32
    Operator (Tasks)
    ^^^^^^^^
IndentationError: expected an indented block after 'with' statement on line 22
[2025-05-22T04:39:55.559+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/(niu)operators.py
[2025-05-22T04:39:55.775+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/(niu)operators.py took 0.237 seconds
[2025-05-22T04:40:26.376+0000] {processor.py:161} INFO - Started process (PID=2904) to work on /opt/airflow/dags/(niu)operators.py
[2025-05-22T04:40:26.381+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/(niu)operators.py for tasks to queue
[2025-05-22T04:40:26.383+0000] {logging_mixin.py:188} INFO - [2025-05-22T04:40:26.382+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/(niu)operators.py
[2025-05-22T04:40:26.411+0000] {logging_mixin.py:188} INFO - [2025-05-22T04:40:26.410+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/(niu)operators.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/(niu)operators.py", line 32
    Operator (Tasks)
    ^^^^^^^^
IndentationError: expected an indented block after 'with' statement on line 22
[2025-05-22T04:40:26.411+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/(niu)operators.py
[2025-05-22T04:40:26.646+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/(niu)operators.py took 0.278 seconds
[2025-05-22T04:40:57.127+0000] {processor.py:161} INFO - Started process (PID=2919) to work on /opt/airflow/dags/(niu)operators.py
[2025-05-22T04:40:57.128+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/(niu)operators.py for tasks to queue
[2025-05-22T04:40:57.129+0000] {logging_mixin.py:188} INFO - [2025-05-22T04:40:57.129+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/(niu)operators.py
[2025-05-22T04:40:57.141+0000] {logging_mixin.py:188} INFO - [2025-05-22T04:40:57.140+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/(niu)operators.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/(niu)operators.py", line 32
    Operator (Tasks)
    ^^^^^^^^
IndentationError: expected an indented block after 'with' statement on line 22
[2025-05-22T04:40:57.141+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/(niu)operators.py
[2025-05-22T04:40:57.335+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/(niu)operators.py took 0.213 seconds
[2025-05-22T04:41:27.801+0000] {processor.py:161} INFO - Started process (PID=2934) to work on /opt/airflow/dags/(niu)operators.py
[2025-05-22T04:41:27.802+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/(niu)operators.py for tasks to queue
[2025-05-22T04:41:27.803+0000] {logging_mixin.py:188} INFO - [2025-05-22T04:41:27.803+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/(niu)operators.py
[2025-05-22T04:41:27.819+0000] {logging_mixin.py:188} INFO - [2025-05-22T04:41:27.818+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/(niu)operators.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/(niu)operators.py", line 32
    Operator (Tasks)
    ^^^^^^^^
IndentationError: expected an indented block after 'with' statement on line 22
[2025-05-22T04:41:27.820+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/(niu)operators.py
[2025-05-22T04:41:28.034+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/(niu)operators.py took 0.239 seconds
[2025-05-22T04:41:58.666+0000] {processor.py:161} INFO - Started process (PID=2949) to work on /opt/airflow/dags/(niu)operators.py
[2025-05-22T04:41:58.667+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/(niu)operators.py for tasks to queue
[2025-05-22T04:41:58.668+0000] {logging_mixin.py:188} INFO - [2025-05-22T04:41:58.668+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/(niu)operators.py
[2025-05-22T04:41:58.683+0000] {logging_mixin.py:188} INFO - [2025-05-22T04:41:58.682+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/(niu)operators.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/(niu)operators.py", line 32
    Operator (Tasks)
    ^^^^^^^^
IndentationError: expected an indented block after 'with' statement on line 22
[2025-05-22T04:41:58.684+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/(niu)operators.py
[2025-05-22T04:41:58.893+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/(niu)operators.py took 0.232 seconds
[2025-05-22T04:42:29.580+0000] {processor.py:161} INFO - Started process (PID=2969) to work on /opt/airflow/dags/(niu)operators.py
[2025-05-22T04:42:29.581+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/(niu)operators.py for tasks to queue
[2025-05-22T04:42:29.581+0000] {logging_mixin.py:188} INFO - [2025-05-22T04:42:29.581+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/(niu)operators.py
[2025-05-22T04:42:29.591+0000] {logging_mixin.py:188} INFO - [2025-05-22T04:42:29.590+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/(niu)operators.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/(niu)operators.py", line 32
    Operator (Tasks)
    ^^^^^^^^
IndentationError: expected an indented block after 'with' statement on line 22
[2025-05-22T04:42:29.591+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/(niu)operators.py
[2025-05-22T04:42:29.854+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/(niu)operators.py took 0.279 seconds
[2025-05-22T04:43:00.508+0000] {processor.py:161} INFO - Started process (PID=2984) to work on /opt/airflow/dags/(niu)operators.py
[2025-05-22T04:43:00.509+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/(niu)operators.py for tasks to queue
[2025-05-22T04:43:00.510+0000] {logging_mixin.py:188} INFO - [2025-05-22T04:43:00.510+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/(niu)operators.py
[2025-05-22T04:43:00.522+0000] {logging_mixin.py:188} INFO - [2025-05-22T04:43:00.521+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/(niu)operators.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/(niu)operators.py", line 32
    Operator (Tasks)
    ^^^^^^^^
IndentationError: expected an indented block after 'with' statement on line 22
[2025-05-22T04:43:00.523+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/(niu)operators.py
[2025-05-22T04:43:00.722+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/(niu)operators.py took 0.218 seconds
[2025-05-22T04:43:31.199+0000] {processor.py:161} INFO - Started process (PID=2999) to work on /opt/airflow/dags/(niu)operators.py
[2025-05-22T04:43:31.200+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/(niu)operators.py for tasks to queue
[2025-05-22T04:43:31.201+0000] {logging_mixin.py:188} INFO - [2025-05-22T04:43:31.201+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/(niu)operators.py
[2025-05-22T04:43:31.222+0000] {logging_mixin.py:188} INFO - [2025-05-22T04:43:31.221+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/(niu)operators.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/(niu)operators.py", line 32
    Operator (Tasks)
    ^^^^^^^^
IndentationError: expected an indented block after 'with' statement on line 22
[2025-05-22T04:43:31.223+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/(niu)operators.py
[2025-05-22T04:43:33.467+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/(niu)operators.py took 2.273 seconds
[2025-05-22T04:44:04.122+0000] {processor.py:161} INFO - Started process (PID=3014) to work on /opt/airflow/dags/(niu)operators.py
[2025-05-22T04:44:04.122+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/(niu)operators.py for tasks to queue
[2025-05-22T04:44:04.123+0000] {logging_mixin.py:188} INFO - [2025-05-22T04:44:04.123+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/(niu)operators.py
[2025-05-22T04:44:04.142+0000] {logging_mixin.py:188} INFO - [2025-05-22T04:44:04.141+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/(niu)operators.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/(niu)operators.py", line 32
    Operator (Tasks)
    ^^^^^^^^
IndentationError: expected an indented block after 'with' statement on line 22
[2025-05-22T04:44:04.143+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/(niu)operators.py
[2025-05-22T04:44:04.357+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/(niu)operators.py took 0.242 seconds
[2025-05-22T04:44:34.879+0000] {processor.py:161} INFO - Started process (PID=3029) to work on /opt/airflow/dags/(niu)operators.py
[2025-05-22T04:44:34.881+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/(niu)operators.py for tasks to queue
[2025-05-22T04:44:34.882+0000] {logging_mixin.py:188} INFO - [2025-05-22T04:44:34.881+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/(niu)operators.py
[2025-05-22T04:44:34.899+0000] {logging_mixin.py:188} INFO - [2025-05-22T04:44:34.898+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/(niu)operators.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/(niu)operators.py", line 32
    Operator (Tasks)
    ^^^^^^^^
IndentationError: expected an indented block after 'with' statement on line 22
[2025-05-22T04:44:34.900+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/(niu)operators.py
[2025-05-22T04:44:35.120+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/(niu)operators.py took 0.248 seconds
[2025-05-22T04:45:05.713+0000] {processor.py:161} INFO - Started process (PID=3044) to work on /opt/airflow/dags/(niu)operators.py
[2025-05-22T04:45:05.715+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/(niu)operators.py for tasks to queue
[2025-05-22T04:45:05.716+0000] {logging_mixin.py:188} INFO - [2025-05-22T04:45:05.715+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/(niu)operators.py
[2025-05-22T04:45:05.734+0000] {logging_mixin.py:188} INFO - [2025-05-22T04:45:05.733+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/(niu)operators.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/(niu)operators.py", line 32
    Operator (Tasks)
    ^^^^^^^^
IndentationError: expected an indented block after 'with' statement on line 22
[2025-05-22T04:45:05.735+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/(niu)operators.py
[2025-05-22T04:45:06.044+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/(niu)operators.py took 0.336 seconds
[2025-05-22T04:45:36.735+0000] {processor.py:161} INFO - Started process (PID=3064) to work on /opt/airflow/dags/(niu)operators.py
[2025-05-22T04:45:36.736+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/(niu)operators.py for tasks to queue
[2025-05-22T04:45:36.737+0000] {logging_mixin.py:188} INFO - [2025-05-22T04:45:36.736+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/(niu)operators.py
[2025-05-22T04:45:36.754+0000] {logging_mixin.py:188} INFO - [2025-05-22T04:45:36.753+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/(niu)operators.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/(niu)operators.py", line 32
    Operator (Tasks)
    ^^^^^^^^
IndentationError: expected an indented block after 'with' statement on line 22
[2025-05-22T04:45:36.754+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/(niu)operators.py
[2025-05-22T04:45:36.940+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/(niu)operators.py took 0.213 seconds
[2025-05-22T04:46:07.640+0000] {processor.py:161} INFO - Started process (PID=3079) to work on /opt/airflow/dags/(niu)operators.py
[2025-05-22T04:46:07.641+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/(niu)operators.py for tasks to queue
[2025-05-22T04:46:07.642+0000] {logging_mixin.py:188} INFO - [2025-05-22T04:46:07.642+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/(niu)operators.py
[2025-05-22T04:46:07.657+0000] {logging_mixin.py:188} INFO - [2025-05-22T04:46:07.656+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/(niu)operators.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/(niu)operators.py", line 32
    Operator (Tasks)
    ^^^^^^^^
IndentationError: expected an indented block after 'with' statement on line 22
[2025-05-22T04:46:07.658+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/(niu)operators.py
[2025-05-22T04:46:07.869+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/(niu)operators.py took 0.234 seconds
[2025-05-22T04:46:38.341+0000] {processor.py:161} INFO - Started process (PID=3094) to work on /opt/airflow/dags/(niu)operators.py
[2025-05-22T04:46:38.342+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/(niu)operators.py for tasks to queue
[2025-05-22T04:46:38.343+0000] {logging_mixin.py:188} INFO - [2025-05-22T04:46:38.343+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/(niu)operators.py
[2025-05-22T04:46:38.360+0000] {logging_mixin.py:188} INFO - [2025-05-22T04:46:38.358+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/(niu)operators.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/(niu)operators.py", line 32
    Operator (Tasks)
    ^^^^^^^^
IndentationError: expected an indented block after 'with' statement on line 22
[2025-05-22T04:46:38.360+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/(niu)operators.py
[2025-05-22T04:46:38.557+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/(niu)operators.py took 0.223 seconds
[2025-05-22T04:47:09.196+0000] {processor.py:161} INFO - Started process (PID=3110) to work on /opt/airflow/dags/(niu)operators.py
[2025-05-22T04:47:09.197+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/(niu)operators.py for tasks to queue
[2025-05-22T04:47:09.198+0000] {logging_mixin.py:188} INFO - [2025-05-22T04:47:09.198+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/(niu)operators.py
[2025-05-22T04:47:09.210+0000] {logging_mixin.py:188} INFO - [2025-05-22T04:47:09.209+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/(niu)operators.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/(niu)operators.py", line 32
    Operator (Tasks)
    ^^^^^^^^
IndentationError: expected an indented block after 'with' statement on line 22
[2025-05-22T04:47:09.210+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/(niu)operators.py
[2025-05-22T04:47:09.426+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/(niu)operators.py took 0.235 seconds
[2025-05-22T04:47:39.979+0000] {processor.py:161} INFO - Started process (PID=3125) to work on /opt/airflow/dags/(niu)operators.py
[2025-05-22T04:47:39.981+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/(niu)operators.py for tasks to queue
[2025-05-22T04:47:39.982+0000] {logging_mixin.py:188} INFO - [2025-05-22T04:47:39.981+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/(niu)operators.py
[2025-05-22T04:47:39.994+0000] {logging_mixin.py:188} INFO - [2025-05-22T04:47:39.992+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/(niu)operators.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/(niu)operators.py", line 32
    Operator (Tasks)
    ^^^^^^^^
IndentationError: expected an indented block after 'with' statement on line 22
[2025-05-22T04:47:39.994+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/(niu)operators.py
[2025-05-22T04:47:40.197+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/(niu)operators.py took 0.223 seconds
[2025-05-22T04:48:10.898+0000] {processor.py:161} INFO - Started process (PID=3140) to work on /opt/airflow/dags/(niu)operators.py
[2025-05-22T04:48:10.899+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/(niu)operators.py for tasks to queue
[2025-05-22T04:48:10.900+0000] {logging_mixin.py:188} INFO - [2025-05-22T04:48:10.900+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/(niu)operators.py
[2025-05-22T04:48:10.917+0000] {logging_mixin.py:188} INFO - [2025-05-22T04:48:10.916+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/(niu)operators.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/(niu)operators.py", line 32
    Operator (Tasks)
    ^^^^^^^^
IndentationError: expected an indented block after 'with' statement on line 22
[2025-05-22T04:48:10.918+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/(niu)operators.py
[2025-05-22T04:48:13.129+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/(niu)operators.py took 2.238 seconds
[2025-05-22T04:48:43.736+0000] {processor.py:161} INFO - Started process (PID=3155) to work on /opt/airflow/dags/(niu)operators.py
[2025-05-22T04:48:43.738+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/(niu)operators.py for tasks to queue
[2025-05-22T04:48:43.739+0000] {logging_mixin.py:188} INFO - [2025-05-22T04:48:43.739+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/(niu)operators.py
[2025-05-22T04:48:43.774+0000] {logging_mixin.py:188} INFO - [2025-05-22T04:48:43.773+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/(niu)operators.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/(niu)operators.py", line 32
    Operator (Tasks)
    ^^^^^^^^
IndentationError: expected an indented block after 'with' statement on line 22
[2025-05-22T04:48:43.775+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/(niu)operators.py
[2025-05-22T04:59:20.470+0000] {processor.py:161} INFO - Started process (PID=179) to work on /opt/airflow/dags/(niu)operators.py
[2025-05-22T04:59:20.473+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/(niu)operators.py for tasks to queue
[2025-05-22T04:59:20.481+0000] {logging_mixin.py:188} INFO - [2025-05-22T04:59:20.480+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/(niu)operators.py
[2025-05-22T04:59:20.506+0000] {logging_mixin.py:188} INFO - [2025-05-22T04:59:20.503+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/(niu)operators.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/(niu)operators.py", line 32
    Operator (Tasks)
    ^^^^^^^^
IndentationError: expected an indented block after 'with' statement on line 22
[2025-05-22T04:59:20.507+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/(niu)operators.py
[2025-05-22T04:59:20.722+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/(niu)operators.py took 0.260 seconds
[2025-05-22T04:59:51.213+0000] {processor.py:161} INFO - Started process (PID=214) to work on /opt/airflow/dags/(niu)operators.py
[2025-05-22T04:59:51.215+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/(niu)operators.py for tasks to queue
[2025-05-22T04:59:51.219+0000] {logging_mixin.py:188} INFO - [2025-05-22T04:59:51.219+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/(niu)operators.py
[2025-05-22T04:59:51.247+0000] {logging_mixin.py:188} INFO - [2025-05-22T04:59:51.246+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/(niu)operators.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/(niu)operators.py", line 32
    Operator (Tasks)
    ^^^^^^^^
IndentationError: expected an indented block after 'with' statement on line 22
[2025-05-22T04:59:51.248+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/(niu)operators.py
[2025-05-22T04:59:51.520+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/(niu)operators.py took 0.312 seconds
[2025-05-22T05:00:22.060+0000] {processor.py:161} INFO - Started process (PID=229) to work on /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:00:22.061+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/(niu)operators.py for tasks to queue
[2025-05-22T05:00:22.063+0000] {logging_mixin.py:188} INFO - [2025-05-22T05:00:22.063+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:00:22.077+0000] {logging_mixin.py:188} INFO - [2025-05-22T05:00:22.076+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/(niu)operators.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/(niu)operators.py", line 32
    Operator (Tasks)
    ^^^^^^^^
IndentationError: expected an indented block after 'with' statement on line 22
[2025-05-22T05:00:22.077+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:00:22.344+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/(niu)operators.py took 0.288 seconds
[2025-05-22T05:00:52.926+0000] {processor.py:161} INFO - Started process (PID=244) to work on /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:00:52.927+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/(niu)operators.py for tasks to queue
[2025-05-22T05:00:52.929+0000] {logging_mixin.py:188} INFO - [2025-05-22T05:00:52.928+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:00:52.951+0000] {logging_mixin.py:188} INFO - [2025-05-22T05:00:52.950+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/(niu)operators.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/(niu)operators.py", line 32
    Operator (Tasks)
    ^^^^^^^^
IndentationError: expected an indented block after 'with' statement on line 22
[2025-05-22T05:00:52.951+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:00:53.319+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/(niu)operators.py took 0.398 seconds
[2025-05-22T05:01:23.766+0000] {processor.py:161} INFO - Started process (PID=259) to work on /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:01:23.767+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/(niu)operators.py for tasks to queue
[2025-05-22T05:01:23.769+0000] {logging_mixin.py:188} INFO - [2025-05-22T05:01:23.768+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:01:23.790+0000] {logging_mixin.py:188} INFO - [2025-05-22T05:01:23.789+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/(niu)operators.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/(niu)operators.py", line 32
    Operator (Tasks)
    ^^^^^^^^
IndentationError: expected an indented block after 'with' statement on line 22
[2025-05-22T05:01:23.790+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:01:24.049+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/(niu)operators.py took 0.288 seconds
[2025-05-22T05:01:54.572+0000] {processor.py:161} INFO - Started process (PID=275) to work on /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:01:54.573+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/(niu)operators.py for tasks to queue
[2025-05-22T05:01:54.574+0000] {logging_mixin.py:188} INFO - [2025-05-22T05:01:54.574+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:01:54.591+0000] {logging_mixin.py:188} INFO - [2025-05-22T05:01:54.590+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/(niu)operators.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/(niu)operators.py", line 32
    Operator (Tasks)
    ^^^^^^^^
IndentationError: expected an indented block after 'with' statement on line 22
[2025-05-22T05:01:54.592+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:01:54.819+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/(niu)operators.py took 0.253 seconds
[2025-05-22T05:02:27.361+0000] {processor.py:161} INFO - Started process (PID=290) to work on /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:02:27.362+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/(niu)operators.py for tasks to queue
[2025-05-22T05:02:27.364+0000] {logging_mixin.py:188} INFO - [2025-05-22T05:02:27.363+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:02:27.378+0000] {logging_mixin.py:188} INFO - [2025-05-22T05:02:27.377+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/(niu)operators.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/(niu)operators.py", line 32
    Operator (Tasks)
    ^^^^^^^^
IndentationError: expected an indented block after 'with' statement on line 22
[2025-05-22T05:02:27.378+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:02:30.494+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/(niu)operators.py took 3.138 seconds
[2025-05-22T05:03:00.913+0000] {processor.py:161} INFO - Started process (PID=305) to work on /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:03:00.913+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/(niu)operators.py for tasks to queue
[2025-05-22T05:03:00.915+0000] {logging_mixin.py:188} INFO - [2025-05-22T05:03:00.915+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:03:00.929+0000] {logging_mixin.py:188} INFO - [2025-05-22T05:03:00.928+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/(niu)operators.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/(niu)operators.py", line 32
    Operator (Tasks)
    ^^^^^^^^
IndentationError: expected an indented block after 'with' statement on line 22
[2025-05-22T05:03:00.930+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:03:01.134+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/(niu)operators.py took 0.226 seconds
[2025-05-22T05:07:06.679+0000] {processor.py:161} INFO - Started process (PID=187) to work on /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:07:06.680+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/(niu)operators.py for tasks to queue
[2025-05-22T05:07:06.682+0000] {logging_mixin.py:188} INFO - [2025-05-22T05:07:06.682+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:07:06.701+0000] {logging_mixin.py:188} INFO - [2025-05-22T05:07:06.699+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/(niu)operators.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/(niu)operators.py", line 32
    Operator (Tasks)
    ^^^^^^^^
IndentationError: expected an indented block after 'with' statement on line 22
[2025-05-22T05:07:06.702+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:07:07.061+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/(niu)operators.py took 0.387 seconds
[2025-05-22T05:07:37.492+0000] {processor.py:161} INFO - Started process (PID=221) to work on /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:07:37.493+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/(niu)operators.py for tasks to queue
[2025-05-22T05:07:37.501+0000] {logging_mixin.py:188} INFO - [2025-05-22T05:07:37.501+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:07:37.525+0000] {logging_mixin.py:188} INFO - [2025-05-22T05:07:37.524+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/(niu)operators.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/(niu)operators.py", line 32
    Operator (Tasks)
    ^^^^^^^^
IndentationError: expected an indented block after 'with' statement on line 22
[2025-05-22T05:07:37.525+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:07:37.761+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/(niu)operators.py took 0.274 seconds
[2025-05-22T05:08:08.494+0000] {processor.py:161} INFO - Started process (PID=236) to work on /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:08:08.495+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/(niu)operators.py for tasks to queue
[2025-05-22T05:08:08.497+0000] {logging_mixin.py:188} INFO - [2025-05-22T05:08:08.496+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:08:08.509+0000] {logging_mixin.py:188} INFO - [2025-05-22T05:08:08.508+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/(niu)operators.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/(niu)operators.py", line 32
    Operator (Tasks)
    ^^^^^^^^
IndentationError: expected an indented block after 'with' statement on line 22
[2025-05-22T05:08:08.509+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:08:08.757+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/(niu)operators.py took 0.267 seconds
[2025-05-22T05:08:39.303+0000] {processor.py:161} INFO - Started process (PID=258) to work on /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:08:39.305+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/(niu)operators.py for tasks to queue
[2025-05-22T05:08:39.306+0000] {logging_mixin.py:188} INFO - [2025-05-22T05:08:39.306+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:08:39.320+0000] {logging_mixin.py:188} INFO - [2025-05-22T05:08:39.319+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/(niu)operators.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/(niu)operators.py", line 32
    Operator (Tasks)
    ^^^^^^^^
IndentationError: expected an indented block after 'with' statement on line 22
[2025-05-22T05:08:39.321+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:08:39.635+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/(niu)operators.py took 0.338 seconds
[2025-05-22T05:09:10.144+0000] {processor.py:161} INFO - Started process (PID=273) to work on /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:09:10.145+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/(niu)operators.py for tasks to queue
[2025-05-22T05:09:10.147+0000] {logging_mixin.py:188} INFO - [2025-05-22T05:09:10.147+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:09:10.164+0000] {logging_mixin.py:188} INFO - [2025-05-22T05:09:10.163+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/(niu)operators.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/(niu)operators.py", line 32
    Operator (Tasks)
    ^^^^^^^^
IndentationError: expected an indented block after 'with' statement on line 22
[2025-05-22T05:09:10.165+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:09:10.393+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/(niu)operators.py took 0.253 seconds
[2025-05-22T05:09:41.163+0000] {processor.py:161} INFO - Started process (PID=292) to work on /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:09:41.164+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/(niu)operators.py for tasks to queue
[2025-05-22T05:09:41.166+0000] {logging_mixin.py:188} INFO - [2025-05-22T05:09:41.165+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:09:41.179+0000] {logging_mixin.py:188} INFO - [2025-05-22T05:09:41.178+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/(niu)operators.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/(niu)operators.py", line 32
    Operator (Tasks)
    ^^^^^^^^
IndentationError: expected an indented block after 'with' statement on line 22
[2025-05-22T05:09:41.179+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:09:41.763+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/(niu)operators.py took 0.604 seconds
[2025-05-22T05:10:12.290+0000] {processor.py:161} INFO - Started process (PID=307) to work on /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:10:12.291+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/(niu)operators.py for tasks to queue
[2025-05-22T05:10:12.293+0000] {logging_mixin.py:188} INFO - [2025-05-22T05:10:12.292+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:10:12.308+0000] {logging_mixin.py:188} INFO - [2025-05-22T05:10:12.306+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/(niu)operators.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/(niu)operators.py", line 32
    Operator (Tasks)
    ^^^^^^^^
IndentationError: expected an indented block after 'with' statement on line 22
[2025-05-22T05:10:12.308+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:10:12.502+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/(niu)operators.py took 0.218 seconds
[2025-05-22T05:10:44.280+0000] {processor.py:161} INFO - Started process (PID=322) to work on /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:10:44.281+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/(niu)operators.py for tasks to queue
[2025-05-22T05:10:44.283+0000] {logging_mixin.py:188} INFO - [2025-05-22T05:10:44.282+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:10:44.297+0000] {logging_mixin.py:188} INFO - [2025-05-22T05:10:44.296+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/(niu)operators.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/(niu)operators.py", line 32
    Operator (Tasks)
    ^^^^^^^^
IndentationError: expected an indented block after 'with' statement on line 22
[2025-05-22T05:10:44.298+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:10:47.401+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/(niu)operators.py took 3.126 seconds
[2025-05-22T05:11:18.024+0000] {processor.py:161} INFO - Started process (PID=339) to work on /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:11:18.025+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/(niu)operators.py for tasks to queue
[2025-05-22T05:11:18.026+0000] {logging_mixin.py:188} INFO - [2025-05-22T05:11:18.026+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:11:18.038+0000] {logging_mixin.py:188} INFO - [2025-05-22T05:11:18.037+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/(niu)operators.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/(niu)operators.py", line 32
    Operator (Tasks)
    ^^^^^^^^
IndentationError: expected an indented block after 'with' statement on line 22
[2025-05-22T05:11:18.038+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:11:18.319+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/(niu)operators.py took 0.299 seconds
[2025-05-22T05:11:48.890+0000] {processor.py:161} INFO - Started process (PID=354) to work on /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:11:48.891+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/(niu)operators.py for tasks to queue
[2025-05-22T05:11:48.893+0000] {logging_mixin.py:188} INFO - [2025-05-22T05:11:48.893+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:11:48.906+0000] {logging_mixin.py:188} INFO - [2025-05-22T05:11:48.905+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/(niu)operators.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/(niu)operators.py", line 32
    Operator (Tasks)
    ^^^^^^^^
IndentationError: expected an indented block after 'with' statement on line 22
[2025-05-22T05:11:48.906+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:11:51.191+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/(niu)operators.py took 2.308 seconds
[2025-05-22T05:12:22.013+0000] {processor.py:161} INFO - Started process (PID=369) to work on /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:12:22.014+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/(niu)operators.py for tasks to queue
[2025-05-22T05:12:22.016+0000] {logging_mixin.py:188} INFO - [2025-05-22T05:12:22.016+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:12:22.031+0000] {logging_mixin.py:188} INFO - [2025-05-22T05:12:22.030+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/(niu)operators.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/(niu)operators.py", line 32
    Operator (Tasks)
    ^^^^^^^^
IndentationError: expected an indented block after 'with' statement on line 22
[2025-05-22T05:12:22.032+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:12:22.274+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/(niu)operators.py took 0.265 seconds
[2025-05-22T05:12:52.830+0000] {processor.py:161} INFO - Started process (PID=384) to work on /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:12:52.830+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/(niu)operators.py for tasks to queue
[2025-05-22T05:12:52.832+0000] {logging_mixin.py:188} INFO - [2025-05-22T05:12:52.832+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:12:52.844+0000] {logging_mixin.py:188} INFO - [2025-05-22T05:12:52.843+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/(niu)operators.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/(niu)operators.py", line 32
    Operator (Tasks)
    ^^^^^^^^
IndentationError: expected an indented block after 'with' statement on line 22
[2025-05-22T05:12:52.844+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:12:53.064+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/(niu)operators.py took 0.239 seconds
[2025-05-22T05:13:23.664+0000] {processor.py:161} INFO - Started process (PID=399) to work on /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:13:23.664+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/(niu)operators.py for tasks to queue
[2025-05-22T05:13:23.666+0000] {logging_mixin.py:188} INFO - [2025-05-22T05:13:23.666+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:13:23.679+0000] {logging_mixin.py:188} INFO - [2025-05-22T05:13:23.678+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/(niu)operators.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/(niu)operators.py", line 32
    Operator (Tasks)
    ^^^^^^^^
IndentationError: expected an indented block after 'with' statement on line 22
[2025-05-22T05:13:23.680+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:13:23.923+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/(niu)operators.py took 0.264 seconds
[2025-05-22T05:13:54.361+0000] {processor.py:161} INFO - Started process (PID=414) to work on /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:13:54.362+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/(niu)operators.py for tasks to queue
[2025-05-22T05:13:54.364+0000] {logging_mixin.py:188} INFO - [2025-05-22T05:13:54.364+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:13:54.383+0000] {logging_mixin.py:188} INFO - [2025-05-22T05:13:54.382+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/(niu)operators.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/(niu)operators.py", line 32
    Operator (Tasks)
    ^^^^^^^^
IndentationError: expected an indented block after 'with' statement on line 22
[2025-05-22T05:13:54.384+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:13:54.612+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/(niu)operators.py took 0.256 seconds
[2025-05-22T05:14:25.122+0000] {processor.py:161} INFO - Started process (PID=429) to work on /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:14:25.123+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/(niu)operators.py for tasks to queue
[2025-05-22T05:14:25.124+0000] {logging_mixin.py:188} INFO - [2025-05-22T05:14:25.124+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:14:25.136+0000] {logging_mixin.py:188} INFO - [2025-05-22T05:14:25.135+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/(niu)operators.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/(niu)operators.py", line 32
    Operator (Tasks)
    ^^^^^^^^
IndentationError: expected an indented block after 'with' statement on line 22
[2025-05-22T05:14:25.136+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:14:25.346+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/(niu)operators.py took 0.229 seconds
[2025-05-22T05:14:55.844+0000] {processor.py:161} INFO - Started process (PID=444) to work on /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:14:55.845+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/(niu)operators.py for tasks to queue
[2025-05-22T05:14:55.847+0000] {logging_mixin.py:188} INFO - [2025-05-22T05:14:55.847+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:14:55.859+0000] {logging_mixin.py:188} INFO - [2025-05-22T05:14:55.858+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/(niu)operators.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/(niu)operators.py", line 32
    Operator (Tasks)
    ^^^^^^^^
IndentationError: expected an indented block after 'with' statement on line 22
[2025-05-22T05:14:55.859+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:14:56.079+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/(niu)operators.py took 0.240 seconds
[2025-05-22T05:15:26.560+0000] {processor.py:161} INFO - Started process (PID=459) to work on /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:15:26.561+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/(niu)operators.py for tasks to queue
[2025-05-22T05:15:26.563+0000] {logging_mixin.py:188} INFO - [2025-05-22T05:15:26.563+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:15:26.587+0000] {logging_mixin.py:188} INFO - [2025-05-22T05:15:26.586+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/(niu)operators.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/(niu)operators.py", line 32
    Operator (Tasks)
    ^^^^^^^^
IndentationError: expected an indented block after 'with' statement on line 22
[2025-05-22T05:15:26.588+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:15:26.788+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/(niu)operators.py took 0.233 seconds
[2025-05-22T05:15:57.231+0000] {processor.py:161} INFO - Started process (PID=474) to work on /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:15:57.232+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/(niu)operators.py for tasks to queue
[2025-05-22T05:15:57.234+0000] {logging_mixin.py:188} INFO - [2025-05-22T05:15:57.234+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:15:57.245+0000] {logging_mixin.py:188} INFO - [2025-05-22T05:15:57.244+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/(niu)operators.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/(niu)operators.py", line 32
    Operator (Tasks)
    ^^^^^^^^
IndentationError: expected an indented block after 'with' statement on line 22
[2025-05-22T05:15:57.245+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:15:57.431+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/(niu)operators.py took 0.205 seconds
[2025-05-22T05:16:28.088+0000] {processor.py:161} INFO - Started process (PID=489) to work on /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:16:28.089+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/(niu)operators.py for tasks to queue
[2025-05-22T05:16:28.090+0000] {logging_mixin.py:188} INFO - [2025-05-22T05:16:28.090+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:16:28.104+0000] {logging_mixin.py:188} INFO - [2025-05-22T05:16:28.103+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/(niu)operators.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/(niu)operators.py", line 32
    Operator (Tasks)
    ^^^^^^^^
IndentationError: expected an indented block after 'with' statement on line 22
[2025-05-22T05:16:28.105+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:16:28.333+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/(niu)operators.py took 0.250 seconds
[2025-05-22T05:16:58.894+0000] {processor.py:161} INFO - Started process (PID=504) to work on /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:16:58.895+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/(niu)operators.py for tasks to queue
[2025-05-22T05:16:58.896+0000] {logging_mixin.py:188} INFO - [2025-05-22T05:16:58.896+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:16:58.911+0000] {logging_mixin.py:188} INFO - [2025-05-22T05:16:58.911+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/(niu)operators.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/(niu)operators.py", line 32
    Operator (Tasks)
    ^^^^^^^^
IndentationError: expected an indented block after 'with' statement on line 22
[2025-05-22T05:16:58.912+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:16:59.113+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/(niu)operators.py took 0.224 seconds
[2025-05-22T05:17:29.532+0000] {processor.py:161} INFO - Started process (PID=517) to work on /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:17:29.533+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/(niu)operators.py for tasks to queue
[2025-05-22T05:17:29.534+0000] {logging_mixin.py:188} INFO - [2025-05-22T05:17:29.534+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:17:29.546+0000] {logging_mixin.py:188} INFO - [2025-05-22T05:17:29.545+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/(niu)operators.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/(niu)operators.py", line 32
    Operator (Tasks)
    ^^^^^^^^
IndentationError: expected an indented block after 'with' statement on line 22
[2025-05-22T05:17:29.546+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:17:32.979+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/(niu)operators.py took 3.451 seconds
[2025-05-22T05:18:03.750+0000] {processor.py:161} INFO - Started process (PID=534) to work on /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:18:03.751+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/(niu)operators.py for tasks to queue
[2025-05-22T05:18:03.754+0000] {logging_mixin.py:188} INFO - [2025-05-22T05:18:03.753+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:18:03.771+0000] {logging_mixin.py:188} INFO - [2025-05-22T05:18:03.770+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/(niu)operators.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/(niu)operators.py", line 32
    Operator (Tasks)
    ^^^^^^^^
IndentationError: expected an indented block after 'with' statement on line 22
[2025-05-22T05:18:03.771+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:18:04.027+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/(niu)operators.py took 0.282 seconds
[2025-05-22T05:18:34.469+0000] {processor.py:161} INFO - Started process (PID=549) to work on /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:18:34.470+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/(niu)operators.py for tasks to queue
[2025-05-22T05:18:34.472+0000] {logging_mixin.py:188} INFO - [2025-05-22T05:18:34.472+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:18:34.488+0000] {logging_mixin.py:188} INFO - [2025-05-22T05:18:34.487+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/(niu)operators.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/(niu)operators.py", line 32
    Operator (Tasks)
    ^^^^^^^^
IndentationError: expected an indented block after 'with' statement on line 22
[2025-05-22T05:18:34.488+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:18:36.753+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/(niu)operators.py took 2.289 seconds
[2025-05-22T05:19:07.174+0000] {processor.py:161} INFO - Started process (PID=564) to work on /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:19:07.175+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/(niu)operators.py for tasks to queue
[2025-05-22T05:19:07.177+0000] {logging_mixin.py:188} INFO - [2025-05-22T05:19:07.176+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:19:07.186+0000] {logging_mixin.py:188} INFO - [2025-05-22T05:19:07.185+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/(niu)operators.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/(niu)operators.py", line 32
    Operator (Tasks)
    ^^^^^^^^
IndentationError: expected an indented block after 'with' statement on line 22
[2025-05-22T05:19:07.187+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:19:07.396+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/(niu)operators.py took 0.226 seconds
[2025-05-22T05:19:37.857+0000] {processor.py:161} INFO - Started process (PID=579) to work on /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:19:37.858+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/(niu)operators.py for tasks to queue
[2025-05-22T05:19:37.859+0000] {logging_mixin.py:188} INFO - [2025-05-22T05:19:37.859+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:19:37.880+0000] {logging_mixin.py:188} INFO - [2025-05-22T05:19:37.877+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/(niu)operators.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/(niu)operators.py", line 32
    Operator (Tasks)
    ^^^^^^^^
IndentationError: expected an indented block after 'with' statement on line 22
[2025-05-22T05:19:37.881+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:19:38.120+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/(niu)operators.py took 0.268 seconds
[2025-05-22T05:20:08.716+0000] {processor.py:161} INFO - Started process (PID=594) to work on /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:20:08.717+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/(niu)operators.py for tasks to queue
[2025-05-22T05:20:08.719+0000] {logging_mixin.py:188} INFO - [2025-05-22T05:20:08.718+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:20:08.735+0000] {logging_mixin.py:188} INFO - [2025-05-22T05:20:08.734+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/(niu)operators.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/(niu)operators.py", line 32
    Operator (Tasks)
    ^^^^^^^^
IndentationError: expected an indented block after 'with' statement on line 22
[2025-05-22T05:20:08.736+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:20:08.951+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/(niu)operators.py took 0.240 seconds
[2025-05-22T05:20:39.419+0000] {processor.py:161} INFO - Started process (PID=609) to work on /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:20:39.420+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/(niu)operators.py for tasks to queue
[2025-05-22T05:20:39.421+0000] {logging_mixin.py:188} INFO - [2025-05-22T05:20:39.421+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:20:39.433+0000] {logging_mixin.py:188} INFO - [2025-05-22T05:20:39.431+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/(niu)operators.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/(niu)operators.py", line 32
    Operator (Tasks)
    ^^^^^^^^
IndentationError: expected an indented block after 'with' statement on line 22
[2025-05-22T05:20:39.434+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:20:39.673+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/(niu)operators.py took 0.259 seconds
[2025-05-22T05:21:10.060+0000] {processor.py:161} INFO - Started process (PID=624) to work on /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:21:10.061+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/(niu)operators.py for tasks to queue
[2025-05-22T05:21:10.062+0000] {logging_mixin.py:188} INFO - [2025-05-22T05:21:10.062+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:21:10.078+0000] {logging_mixin.py:188} INFO - [2025-05-22T05:21:10.077+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/(niu)operators.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/(niu)operators.py", line 32
    Operator (Tasks)
    ^^^^^^^^
IndentationError: expected an indented block after 'with' statement on line 22
[2025-05-22T05:21:10.079+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:21:10.285+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/(niu)operators.py took 0.231 seconds
[2025-05-22T05:21:40.852+0000] {processor.py:161} INFO - Started process (PID=639) to work on /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:21:40.852+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/(niu)operators.py for tasks to queue
[2025-05-22T05:21:40.854+0000] {logging_mixin.py:188} INFO - [2025-05-22T05:21:40.854+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:21:40.866+0000] {logging_mixin.py:188} INFO - [2025-05-22T05:21:40.865+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/(niu)operators.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/(niu)operators.py", line 32
    Operator (Tasks)
    ^^^^^^^^
IndentationError: expected an indented block after 'with' statement on line 22
[2025-05-22T05:21:40.867+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:21:41.122+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/(niu)operators.py took 0.275 seconds
[2025-05-22T05:22:11.521+0000] {processor.py:161} INFO - Started process (PID=654) to work on /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:22:11.522+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/(niu)operators.py for tasks to queue
[2025-05-22T05:22:11.524+0000] {logging_mixin.py:188} INFO - [2025-05-22T05:22:11.524+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:22:11.539+0000] {logging_mixin.py:188} INFO - [2025-05-22T05:22:11.538+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/(niu)operators.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/(niu)operators.py", line 32
    Operator (Tasks)
    ^^^^^^^^
IndentationError: expected an indented block after 'with' statement on line 22
[2025-05-22T05:22:11.540+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:22:11.764+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/(niu)operators.py took 0.248 seconds
[2025-05-22T05:22:42.402+0000] {processor.py:161} INFO - Started process (PID=669) to work on /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:22:42.403+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/(niu)operators.py for tasks to queue
[2025-05-22T05:22:42.405+0000] {logging_mixin.py:188} INFO - [2025-05-22T05:22:42.405+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:22:42.419+0000] {logging_mixin.py:188} INFO - [2025-05-22T05:22:42.419+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/(niu)operators.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/(niu)operators.py", line 32
    Operator (Tasks)
    ^^^^^^^^
IndentationError: expected an indented block after 'with' statement on line 22
[2025-05-22T05:22:42.420+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:22:42.620+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/(niu)operators.py took 0.223 seconds
[2025-05-22T05:23:13.229+0000] {processor.py:161} INFO - Started process (PID=684) to work on /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:23:13.230+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/(niu)operators.py for tasks to queue
[2025-05-22T05:23:13.233+0000] {logging_mixin.py:188} INFO - [2025-05-22T05:23:13.232+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:23:13.256+0000] {logging_mixin.py:188} INFO - [2025-05-22T05:23:13.255+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/(niu)operators.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/(niu)operators.py", line 32
    Operator (Tasks)
    ^^^^^^^^
IndentationError: expected an indented block after 'with' statement on line 22
[2025-05-22T05:23:13.257+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:23:14.553+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/(niu)operators.py took 1.331 seconds
[2025-05-22T05:23:45.064+0000] {processor.py:161} INFO - Started process (PID=699) to work on /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:23:45.065+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/(niu)operators.py for tasks to queue
[2025-05-22T05:23:45.066+0000] {logging_mixin.py:188} INFO - [2025-05-22T05:23:45.066+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:23:45.079+0000] {logging_mixin.py:188} INFO - [2025-05-22T05:23:45.077+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/(niu)operators.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/(niu)operators.py", line 32
    Operator (Tasks)
    ^^^^^^^^
IndentationError: expected an indented block after 'with' statement on line 22
[2025-05-22T05:23:45.080+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:23:45.282+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/(niu)operators.py took 0.223 seconds
[2025-05-22T05:24:15.766+0000] {processor.py:161} INFO - Started process (PID=714) to work on /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:24:15.767+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/(niu)operators.py for tasks to queue
[2025-05-22T05:24:15.769+0000] {logging_mixin.py:188} INFO - [2025-05-22T05:24:15.768+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:24:15.782+0000] {logging_mixin.py:188} INFO - [2025-05-22T05:24:15.782+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/(niu)operators.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/(niu)operators.py", line 32
    Operator (Tasks)
    ^^^^^^^^
IndentationError: expected an indented block after 'with' statement on line 22
[2025-05-22T05:24:15.783+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:24:18.030+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/(niu)operators.py took 2.269 seconds
[2025-05-22T05:24:48.431+0000] {processor.py:161} INFO - Started process (PID=729) to work on /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:24:48.432+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/(niu)operators.py for tasks to queue
[2025-05-22T05:24:48.433+0000] {logging_mixin.py:188} INFO - [2025-05-22T05:24:48.433+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:24:48.445+0000] {logging_mixin.py:188} INFO - [2025-05-22T05:24:48.444+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/(niu)operators.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/(niu)operators.py", line 32
    Operator (Tasks)
    ^^^^^^^^
IndentationError: expected an indented block after 'with' statement on line 22
[2025-05-22T05:24:48.445+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:24:48.692+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/(niu)operators.py took 0.266 seconds
[2025-05-22T05:25:19.103+0000] {processor.py:161} INFO - Started process (PID=744) to work on /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:25:19.104+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/(niu)operators.py for tasks to queue
[2025-05-22T05:25:19.106+0000] {logging_mixin.py:188} INFO - [2025-05-22T05:25:19.105+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:25:19.116+0000] {logging_mixin.py:188} INFO - [2025-05-22T05:25:19.115+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/(niu)operators.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/(niu)operators.py", line 32
    Operator (Tasks)
    ^^^^^^^^
IndentationError: expected an indented block after 'with' statement on line 22
[2025-05-22T05:25:19.117+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:25:19.351+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/(niu)operators.py took 0.252 seconds
[2025-05-22T05:25:49.770+0000] {processor.py:161} INFO - Started process (PID=759) to work on /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:25:49.771+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/(niu)operators.py for tasks to queue
[2025-05-22T05:25:49.773+0000] {logging_mixin.py:188} INFO - [2025-05-22T05:25:49.772+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:25:49.791+0000] {logging_mixin.py:188} INFO - [2025-05-22T05:25:49.789+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/(niu)operators.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/(niu)operators.py", line 32
    Operator (Tasks)
    ^^^^^^^^
IndentationError: expected an indented block after 'with' statement on line 22
[2025-05-22T05:25:49.792+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:25:50.016+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/(niu)operators.py took 0.251 seconds
[2025-05-22T05:26:20.410+0000] {processor.py:161} INFO - Started process (PID=774) to work on /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:26:20.411+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/(niu)operators.py for tasks to queue
[2025-05-22T05:26:20.413+0000] {logging_mixin.py:188} INFO - [2025-05-22T05:26:20.412+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:26:20.423+0000] {logging_mixin.py:188} INFO - [2025-05-22T05:26:20.422+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/(niu)operators.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/(niu)operators.py", line 32
    Operator (Tasks)
    ^^^^^^^^
IndentationError: expected an indented block after 'with' statement on line 22
[2025-05-22T05:26:20.424+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:26:20.697+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/(niu)operators.py took 0.292 seconds
[2025-05-22T05:26:51.071+0000] {processor.py:161} INFO - Started process (PID=789) to work on /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:26:51.072+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/(niu)operators.py for tasks to queue
[2025-05-22T05:26:51.074+0000] {logging_mixin.py:188} INFO - [2025-05-22T05:26:51.074+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:26:51.095+0000] {logging_mixin.py:188} INFO - [2025-05-22T05:26:51.093+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/(niu)operators.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/(niu)operators.py", line 32
    Operator (Tasks)
    ^^^^^^^^
IndentationError: expected an indented block after 'with' statement on line 22
[2025-05-22T05:26:51.095+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:26:51.357+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/(niu)operators.py took 0.292 seconds
[2025-05-22T05:27:22.144+0000] {processor.py:161} INFO - Started process (PID=804) to work on /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:27:22.145+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/(niu)operators.py for tasks to queue
[2025-05-22T05:27:22.147+0000] {logging_mixin.py:188} INFO - [2025-05-22T05:27:22.147+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:27:22.158+0000] {logging_mixin.py:188} INFO - [2025-05-22T05:27:22.157+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/(niu)operators.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/(niu)operators.py", line 32
    Operator (Tasks)
    ^^^^^^^^
IndentationError: expected an indented block after 'with' statement on line 22
[2025-05-22T05:27:22.159+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:27:22.386+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/(niu)operators.py took 0.247 seconds
[2025-05-22T05:27:52.995+0000] {processor.py:161} INFO - Started process (PID=819) to work on /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:27:52.996+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/(niu)operators.py for tasks to queue
[2025-05-22T05:27:52.998+0000] {logging_mixin.py:188} INFO - [2025-05-22T05:27:52.998+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:27:53.009+0000] {logging_mixin.py:188} INFO - [2025-05-22T05:27:53.008+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/(niu)operators.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/(niu)operators.py", line 32
    Operator (Tasks)
    ^^^^^^^^
IndentationError: expected an indented block after 'with' statement on line 22
[2025-05-22T05:27:53.009+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:27:53.222+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/(niu)operators.py took 0.232 seconds
[2025-05-22T05:28:23.851+0000] {processor.py:161} INFO - Started process (PID=834) to work on /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:28:23.851+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/(niu)operators.py for tasks to queue
[2025-05-22T05:28:23.853+0000] {logging_mixin.py:188} INFO - [2025-05-22T05:28:23.852+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:28:23.863+0000] {logging_mixin.py:188} INFO - [2025-05-22T05:28:23.863+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/(niu)operators.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/(niu)operators.py", line 32
    Operator (Tasks)
    ^^^^^^^^
IndentationError: expected an indented block after 'with' statement on line 22
[2025-05-22T05:28:23.864+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:28:24.084+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/(niu)operators.py took 0.239 seconds
[2025-05-22T05:28:54.744+0000] {processor.py:161} INFO - Started process (PID=849) to work on /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:28:54.745+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/(niu)operators.py for tasks to queue
[2025-05-22T05:28:54.747+0000] {logging_mixin.py:188} INFO - [2025-05-22T05:28:54.747+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:28:54.762+0000] {logging_mixin.py:188} INFO - [2025-05-22T05:28:54.761+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/(niu)operators.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/(niu)operators.py", line 32
    Operator (Tasks)
    ^^^^^^^^
IndentationError: expected an indented block after 'with' statement on line 22
[2025-05-22T05:28:54.763+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:28:54.996+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/(niu)operators.py took 0.259 seconds
[2025-05-22T05:29:25.580+0000] {processor.py:161} INFO - Started process (PID=864) to work on /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:29:25.582+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/(niu)operators.py for tasks to queue
[2025-05-22T05:29:25.583+0000] {logging_mixin.py:188} INFO - [2025-05-22T05:29:25.583+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:29:25.596+0000] {logging_mixin.py:188} INFO - [2025-05-22T05:29:25.595+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/(niu)operators.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/(niu)operators.py", line 32
    Operator (Tasks)
    ^^^^^^^^
IndentationError: expected an indented block after 'with' statement on line 22
[2025-05-22T05:29:25.597+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:29:25.824+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/(niu)operators.py took 0.249 seconds
[2025-05-22T05:29:55.982+0000] {processor.py:161} INFO - Started process (PID=879) to work on /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:29:55.983+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/(niu)operators.py for tasks to queue
[2025-05-22T05:29:55.985+0000] {logging_mixin.py:188} INFO - [2025-05-22T05:29:55.985+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:29:55.997+0000] {logging_mixin.py:188} INFO - [2025-05-22T05:29:55.996+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/(niu)operators.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/(niu)operators.py", line 32
    Operator (Tasks)
    ^^^^^^^^
IndentationError: expected an indented block after 'with' statement on line 22
[2025-05-22T05:29:55.998+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:29:58.193+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/(niu)operators.py took 2.216 seconds
[2025-05-22T05:30:28.916+0000] {processor.py:161} INFO - Started process (PID=894) to work on /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:30:28.917+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/(niu)operators.py for tasks to queue
[2025-05-22T05:30:28.920+0000] {logging_mixin.py:188} INFO - [2025-05-22T05:30:28.919+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:30:28.935+0000] {logging_mixin.py:188} INFO - [2025-05-22T05:30:28.934+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/(niu)operators.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/(niu)operators.py", line 32
    Operator (Tasks)
    ^^^^^^^^
IndentationError: expected an indented block after 'with' statement on line 22
[2025-05-22T05:30:28.936+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:30:29.185+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/(niu)operators.py took 0.275 seconds
[2025-05-22T05:31:00.066+0000] {processor.py:161} INFO - Started process (PID=909) to work on /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:31:00.068+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/(niu)operators.py for tasks to queue
[2025-05-22T05:31:00.070+0000] {logging_mixin.py:188} INFO - [2025-05-22T05:31:00.070+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:31:00.110+0000] {logging_mixin.py:188} INFO - [2025-05-22T05:31:00.108+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/(niu)operators.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/(niu)operators.py", line 32
    Operator (Tasks)
    ^^^^^^^^
IndentationError: expected an indented block after 'with' statement on line 22
[2025-05-22T05:31:00.110+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:31:00.500+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/(niu)operators.py took 0.449 seconds
[2025-05-22T05:31:30.674+0000] {processor.py:161} INFO - Started process (PID=924) to work on /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:31:30.675+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/(niu)operators.py for tasks to queue
[2025-05-22T05:31:30.677+0000] {logging_mixin.py:188} INFO - [2025-05-22T05:31:30.677+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:31:30.695+0000] {logging_mixin.py:188} INFO - [2025-05-22T05:31:30.693+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/(niu)operators.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/(niu)operators.py", line 32
    Operator (Tasks)
    ^^^^^^^^
IndentationError: expected an indented block after 'with' statement on line 22
[2025-05-22T05:31:30.696+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:31:30.911+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/(niu)operators.py took 0.242 seconds
[2025-05-22T05:32:01.515+0000] {processor.py:161} INFO - Started process (PID=939) to work on /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:32:01.516+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/(niu)operators.py for tasks to queue
[2025-05-22T05:32:01.519+0000] {logging_mixin.py:188} INFO - [2025-05-22T05:32:01.518+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:32:01.533+0000] {logging_mixin.py:188} INFO - [2025-05-22T05:32:01.532+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/(niu)operators.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/(niu)operators.py", line 32
    Operator (Tasks)
    ^^^^^^^^
IndentationError: expected an indented block after 'with' statement on line 22
[2025-05-22T05:32:01.534+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:32:01.732+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/(niu)operators.py took 0.222 seconds
[2025-05-22T05:32:31.907+0000] {processor.py:161} INFO - Started process (PID=959) to work on /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:32:31.908+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/(niu)operators.py for tasks to queue
[2025-05-22T05:32:31.910+0000] {logging_mixin.py:188} INFO - [2025-05-22T05:32:31.910+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:32:31.924+0000] {logging_mixin.py:188} INFO - [2025-05-22T05:32:31.923+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/(niu)operators.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/(niu)operators.py", line 32
    Operator (Tasks)
    ^^^^^^^^
IndentationError: expected an indented block after 'with' statement on line 22
[2025-05-22T05:32:31.924+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:32:32.128+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/(niu)operators.py took 0.226 seconds
[2025-05-22T05:33:02.850+0000] {processor.py:161} INFO - Started process (PID=979) to work on /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:33:02.851+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/(niu)operators.py for tasks to queue
[2025-05-22T05:33:02.852+0000] {logging_mixin.py:188} INFO - [2025-05-22T05:33:02.852+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:33:02.868+0000] {logging_mixin.py:188} INFO - [2025-05-22T05:33:02.867+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/(niu)operators.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/(niu)operators.py", line 32
    Operator (Tasks)
    ^^^^^^^^
IndentationError: expected an indented block after 'with' statement on line 22
[2025-05-22T05:33:02.869+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:33:03.088+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/(niu)operators.py took 0.243 seconds
[2025-05-22T05:33:33.823+0000] {processor.py:161} INFO - Started process (PID=999) to work on /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:33:33.824+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/(niu)operators.py for tasks to queue
[2025-05-22T05:33:33.826+0000] {logging_mixin.py:188} INFO - [2025-05-22T05:33:33.826+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:33:33.840+0000] {logging_mixin.py:188} INFO - [2025-05-22T05:33:33.839+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/(niu)operators.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/(niu)operators.py", line 32
    Operator (Tasks)
    ^^^^^^^^
IndentationError: expected an indented block after 'with' statement on line 22
[2025-05-22T05:33:33.840+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:33:34.026+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/(niu)operators.py took 0.208 seconds
[2025-05-22T05:34:04.749+0000] {processor.py:161} INFO - Started process (PID=1019) to work on /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:34:04.750+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/(niu)operators.py for tasks to queue
[2025-05-22T05:34:04.752+0000] {logging_mixin.py:188} INFO - [2025-05-22T05:34:04.752+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:34:04.768+0000] {logging_mixin.py:188} INFO - [2025-05-22T05:34:04.767+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/(niu)operators.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/(niu)operators.py", line 32
    Operator (Tasks)
    ^^^^^^^^
IndentationError: expected an indented block after 'with' statement on line 22
[2025-05-22T05:34:04.769+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:34:05.020+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/(niu)operators.py took 0.276 seconds
[2025-05-22T05:34:35.533+0000] {processor.py:161} INFO - Started process (PID=1042) to work on /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:34:35.534+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/(niu)operators.py for tasks to queue
[2025-05-22T05:34:35.536+0000] {logging_mixin.py:188} INFO - [2025-05-22T05:34:35.536+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:34:35.550+0000] {logging_mixin.py:188} INFO - [2025-05-22T05:34:35.549+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/(niu)operators.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/(niu)operators.py", line 32
    Operator (Tasks)
    ^^^^^^^^
IndentationError: expected an indented block after 'with' statement on line 22
[2025-05-22T05:34:35.551+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:34:38.006+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/(niu)operators.py took 2.478 seconds
[2025-05-22T05:35:08.065+0000] {processor.py:161} INFO - Started process (PID=1064) to work on /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:35:08.066+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/(niu)operators.py for tasks to queue
[2025-05-22T05:35:08.068+0000] {logging_mixin.py:188} INFO - [2025-05-22T05:35:08.068+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:35:08.082+0000] {logging_mixin.py:188} INFO - [2025-05-22T05:35:08.081+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/(niu)operators.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/(niu)operators.py", line 32
    Operator (Tasks)
    ^^^^^^^^
IndentationError: expected an indented block after 'with' statement on line 22
[2025-05-22T05:35:08.082+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:35:08.341+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/(niu)operators.py took 0.281 seconds
[2025-05-22T05:35:39.049+0000] {processor.py:161} INFO - Started process (PID=1084) to work on /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:35:39.050+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/(niu)operators.py for tasks to queue
[2025-05-22T05:35:39.052+0000] {logging_mixin.py:188} INFO - [2025-05-22T05:35:39.052+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:35:39.068+0000] {logging_mixin.py:188} INFO - [2025-05-22T05:35:39.066+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/(niu)operators.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/(niu)operators.py", line 32
    Operator (Tasks)
    ^^^^^^^^
IndentationError: expected an indented block after 'with' statement on line 22
[2025-05-22T05:35:39.068+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:36:18.309+0000] {processor.py:161} INFO - Started process (PID=191) to work on /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:36:18.311+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/(niu)operators.py for tasks to queue
[2025-05-22T05:36:18.312+0000] {logging_mixin.py:188} INFO - [2025-05-22T05:36:18.312+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:36:18.327+0000] {logging_mixin.py:188} INFO - [2025-05-22T05:36:18.326+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/(niu)operators.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/(niu)operators.py", line 32
    Operator (Tasks)
    ^^^^^^^^
IndentationError: expected an indented block after 'with' statement on line 22
[2025-05-22T05:36:18.327+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:36:18.542+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/(niu)operators.py took 0.239 seconds
[2025-05-22T05:36:53.477+0000] {processor.py:161} INFO - Started process (PID=231) to work on /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:36:53.478+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/(niu)operators.py for tasks to queue
[2025-05-22T05:36:53.480+0000] {logging_mixin.py:188} INFO - [2025-05-22T05:36:53.479+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:36:53.495+0000] {logging_mixin.py:188} INFO - [2025-05-22T05:36:53.494+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/(niu)operators.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/(niu)operators.py", line 32
    Operator (Tasks)
    ^^^^^^^^
IndentationError: expected an indented block after 'with' statement on line 22
[2025-05-22T05:36:53.496+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:36:54.277+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/(niu)operators.py took 0.805 seconds
[2025-05-22T05:37:24.843+0000] {processor.py:161} INFO - Started process (PID=251) to work on /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:37:24.844+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/(niu)operators.py for tasks to queue
[2025-05-22T05:37:24.846+0000] {logging_mixin.py:188} INFO - [2025-05-22T05:37:24.845+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:37:24.863+0000] {logging_mixin.py:188} INFO - [2025-05-22T05:37:24.862+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/(niu)operators.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/(niu)operators.py", line 32
    Operator (Tasks)
    ^^^^^^^^
IndentationError: expected an indented block after 'with' statement on line 22
[2025-05-22T05:37:24.864+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:37:25.224+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/(niu)operators.py took 0.388 seconds
[2025-05-22T05:37:57.140+0000] {processor.py:161} INFO - Started process (PID=271) to work on /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:37:57.141+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/(niu)operators.py for tasks to queue
[2025-05-22T05:37:57.143+0000] {logging_mixin.py:188} INFO - [2025-05-22T05:37:57.142+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:37:57.175+0000] {logging_mixin.py:188} INFO - [2025-05-22T05:37:57.174+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/(niu)operators.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/(niu)operators.py", line 32
    Operator (Tasks)
    ^^^^^^^^
IndentationError: expected an indented block after 'with' statement on line 22
[2025-05-22T05:37:57.176+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:37:59.518+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/(niu)operators.py took 2.383 seconds
[2025-05-22T05:38:29.634+0000] {processor.py:161} INFO - Started process (PID=293) to work on /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:38:29.635+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/(niu)operators.py for tasks to queue
[2025-05-22T05:38:29.637+0000] {logging_mixin.py:188} INFO - [2025-05-22T05:38:29.637+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:38:29.649+0000] {logging_mixin.py:188} INFO - [2025-05-22T05:38:29.648+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/(niu)operators.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/(niu)operators.py", line 32
    Operator (Tasks)
    ^^^^^^^^
IndentationError: expected an indented block after 'with' statement on line 22
[2025-05-22T05:38:29.649+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:38:29.904+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/(niu)operators.py took 0.276 seconds
[2025-05-22T05:38:59.977+0000] {processor.py:161} INFO - Started process (PID=311) to work on /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:38:59.977+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/(niu)operators.py for tasks to queue
[2025-05-22T05:38:59.980+0000] {logging_mixin.py:188} INFO - [2025-05-22T05:38:59.979+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:38:59.996+0000] {logging_mixin.py:188} INFO - [2025-05-22T05:38:59.995+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/(niu)operators.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/(niu)operators.py", line 32
    Operator (Tasks)
    ^^^^^^^^
IndentationError: expected an indented block after 'with' statement on line 22
[2025-05-22T05:38:59.997+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:39:04.387+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/(niu)operators.py took 4.415 seconds
[2025-05-22T05:39:34.962+0000] {processor.py:161} INFO - Started process (PID=333) to work on /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:39:34.963+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/(niu)operators.py for tasks to queue
[2025-05-22T05:39:34.965+0000] {logging_mixin.py:188} INFO - [2025-05-22T05:39:34.965+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:39:34.980+0000] {logging_mixin.py:188} INFO - [2025-05-22T05:39:34.979+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/(niu)operators.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/(niu)operators.py", line 32
    Operator (Tasks)
    ^^^^^^^^
IndentationError: expected an indented block after 'with' statement on line 22
[2025-05-22T05:39:34.981+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:39:35.198+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/(niu)operators.py took 0.241 seconds
[2025-05-22T05:40:05.985+0000] {processor.py:161} INFO - Started process (PID=353) to work on /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:40:05.987+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/(niu)operators.py for tasks to queue
[2025-05-22T05:40:05.989+0000] {logging_mixin.py:188} INFO - [2025-05-22T05:40:05.989+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:40:06.006+0000] {logging_mixin.py:188} INFO - [2025-05-22T05:40:06.005+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/(niu)operators.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/(niu)operators.py", line 32
    Operator (Tasks)
    ^^^^^^^^
IndentationError: expected an indented block after 'with' statement on line 22
[2025-05-22T05:40:06.007+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:40:08.245+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/(niu)operators.py took 2.266 seconds
[2025-05-22T05:40:38.545+0000] {processor.py:161} INFO - Started process (PID=374) to work on /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:40:38.547+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/(niu)operators.py for tasks to queue
[2025-05-22T05:40:38.549+0000] {logging_mixin.py:188} INFO - [2025-05-22T05:40:38.549+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:40:38.570+0000] {logging_mixin.py:188} INFO - [2025-05-22T05:40:38.569+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/(niu)operators.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/(niu)operators.py", line 32
    Operator (Tasks)
    ^^^^^^^^
IndentationError: expected an indented block after 'with' statement on line 22
[2025-05-22T05:40:38.571+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:40:38.805+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/(niu)operators.py took 0.268 seconds
[2025-05-22T05:41:09.030+0000] {processor.py:161} INFO - Started process (PID=400) to work on /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:41:09.031+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/(niu)operators.py for tasks to queue
[2025-05-22T05:41:09.033+0000] {logging_mixin.py:188} INFO - [2025-05-22T05:41:09.033+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:41:09.046+0000] {logging_mixin.py:188} INFO - [2025-05-22T05:41:09.045+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/(niu)operators.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/(niu)operators.py", line 32
    Operator (Tasks)
    ^^^^^^^^
IndentationError: expected an indented block after 'with' statement on line 22
[2025-05-22T05:41:09.046+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:41:09.290+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/(niu)operators.py took 0.266 seconds
[2025-05-22T05:41:39.896+0000] {processor.py:161} INFO - Started process (PID=420) to work on /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:41:39.897+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/(niu)operators.py for tasks to queue
[2025-05-22T05:41:39.898+0000] {logging_mixin.py:188} INFO - [2025-05-22T05:41:39.898+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:41:39.911+0000] {logging_mixin.py:188} INFO - [2025-05-22T05:41:39.908+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/(niu)operators.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/(niu)operators.py", line 32
    Operator (Tasks)
    ^^^^^^^^
IndentationError: expected an indented block after 'with' statement on line 22
[2025-05-22T05:41:39.911+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:41:40.104+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/(niu)operators.py took 0.214 seconds
[2025-05-22T05:42:10.241+0000] {processor.py:161} INFO - Started process (PID=446) to work on /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:42:10.243+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/(niu)operators.py for tasks to queue
[2025-05-22T05:42:10.245+0000] {logging_mixin.py:188} INFO - [2025-05-22T05:42:10.245+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:42:10.261+0000] {logging_mixin.py:188} INFO - [2025-05-22T05:42:10.260+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/(niu)operators.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/(niu)operators.py", line 32
    Operator (Tasks)
    ^^^^^^^^
IndentationError: expected an indented block after 'with' statement on line 22
[2025-05-22T05:42:10.262+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:42:10.753+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/(niu)operators.py took 0.520 seconds
[2025-05-22T05:42:41.027+0000] {processor.py:161} INFO - Started process (PID=468) to work on /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:42:41.029+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/(niu)operators.py for tasks to queue
[2025-05-22T05:42:41.033+0000] {logging_mixin.py:188} INFO - [2025-05-22T05:42:41.032+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:42:41.070+0000] {logging_mixin.py:188} INFO - [2025-05-22T05:42:41.069+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/(niu)operators.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/(niu)operators.py", line 32
    Operator (Tasks)
    ^^^^^^^^
IndentationError: expected an indented block after 'with' statement on line 22
[2025-05-22T05:42:41.071+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:42:41.297+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/(niu)operators.py took 0.275 seconds
[2025-05-22T05:43:11.449+0000] {processor.py:161} INFO - Started process (PID=488) to work on /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:43:11.450+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/(niu)operators.py for tasks to queue
[2025-05-22T05:43:11.451+0000] {logging_mixin.py:188} INFO - [2025-05-22T05:43:11.451+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:43:11.467+0000] {logging_mixin.py:188} INFO - [2025-05-22T05:43:11.466+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/(niu)operators.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/(niu)operators.py", line 32
    Operator (Tasks)
    ^^^^^^^^
IndentationError: expected an indented block after 'with' statement on line 22
[2025-05-22T05:43:11.467+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:43:11.713+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/(niu)operators.py took 0.270 seconds
[2025-05-22T05:43:42.186+0000] {processor.py:161} INFO - Started process (PID=508) to work on /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:43:42.187+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/(niu)operators.py for tasks to queue
[2025-05-22T05:43:42.188+0000] {logging_mixin.py:188} INFO - [2025-05-22T05:43:42.188+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:43:42.199+0000] {logging_mixin.py:188} INFO - [2025-05-22T05:43:42.198+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/(niu)operators.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/(niu)operators.py", line 32
    Operator (Tasks)
    ^^^^^^^^
IndentationError: expected an indented block after 'with' statement on line 22
[2025-05-22T05:43:42.200+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:43:42.474+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/(niu)operators.py took 0.294 seconds
[2025-05-22T05:44:13.079+0000] {processor.py:161} INFO - Started process (PID=528) to work on /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:44:13.080+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/(niu)operators.py for tasks to queue
[2025-05-22T05:44:13.081+0000] {logging_mixin.py:188} INFO - [2025-05-22T05:44:13.081+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:44:13.096+0000] {logging_mixin.py:188} INFO - [2025-05-22T05:44:13.095+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/(niu)operators.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/(niu)operators.py", line 32
    Operator (Tasks)
    ^^^^^^^^
IndentationError: expected an indented block after 'with' statement on line 22
[2025-05-22T05:44:13.096+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:44:13.285+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/(niu)operators.py took 0.211 seconds
[2025-05-22T05:44:43.758+0000] {processor.py:161} INFO - Started process (PID=548) to work on /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:44:43.759+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/(niu)operators.py for tasks to queue
[2025-05-22T05:44:43.761+0000] {logging_mixin.py:188} INFO - [2025-05-22T05:44:43.761+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:44:43.774+0000] {logging_mixin.py:188} INFO - [2025-05-22T05:44:43.773+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/(niu)operators.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/(niu)operators.py", line 32
    Operator (Tasks)
    ^^^^^^^^
IndentationError: expected an indented block after 'with' statement on line 22
[2025-05-22T05:44:43.774+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:44:44.123+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/(niu)operators.py took 0.369 seconds
[2025-05-22T05:45:14.403+0000] {processor.py:161} INFO - Started process (PID=568) to work on /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:45:14.404+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/(niu)operators.py for tasks to queue
[2025-05-22T05:45:14.406+0000] {logging_mixin.py:188} INFO - [2025-05-22T05:45:14.405+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:45:14.420+0000] {logging_mixin.py:188} INFO - [2025-05-22T05:45:14.419+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/(niu)operators.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/(niu)operators.py", line 32
    Operator (Tasks)
    ^^^^^^^^
IndentationError: expected an indented block after 'with' statement on line 22
[2025-05-22T05:45:14.421+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:45:14.661+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/(niu)operators.py took 0.263 seconds
[2025-05-22T05:45:45.253+0000] {processor.py:161} INFO - Started process (PID=588) to work on /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:45:45.254+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/(niu)operators.py for tasks to queue
[2025-05-22T05:45:45.255+0000] {logging_mixin.py:188} INFO - [2025-05-22T05:45:45.255+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:45:45.270+0000] {logging_mixin.py:188} INFO - [2025-05-22T05:45:45.269+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/(niu)operators.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/(niu)operators.py", line 32
    Operator (Tasks)
    ^^^^^^^^
IndentationError: expected an indented block after 'with' statement on line 22
[2025-05-22T05:45:45.271+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:45:45.468+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/(niu)operators.py took 0.219 seconds
[2025-05-22T05:46:15.621+0000] {processor.py:161} INFO - Started process (PID=608) to work on /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:46:15.622+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/(niu)operators.py for tasks to queue
[2025-05-22T05:46:15.623+0000] {logging_mixin.py:188} INFO - [2025-05-22T05:46:15.623+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:46:15.637+0000] {logging_mixin.py:188} INFO - [2025-05-22T05:46:15.636+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/(niu)operators.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/(niu)operators.py", line 32
    Operator (Tasks)
    ^^^^^^^^
IndentationError: expected an indented block after 'with' statement on line 22
[2025-05-22T05:46:15.638+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:46:15.880+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/(niu)operators.py took 0.264 seconds
[2025-05-22T05:46:46.081+0000] {processor.py:161} INFO - Started process (PID=628) to work on /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:46:46.082+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/(niu)operators.py for tasks to queue
[2025-05-22T05:46:46.084+0000] {logging_mixin.py:188} INFO - [2025-05-22T05:46:46.083+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:46:46.096+0000] {logging_mixin.py:188} INFO - [2025-05-22T05:46:46.095+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/(niu)operators.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/(niu)operators.py", line 32
    Operator (Tasks)
    ^^^^^^^^
IndentationError: expected an indented block after 'with' statement on line 22
[2025-05-22T05:46:46.096+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:46:46.341+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/(niu)operators.py took 0.266 seconds
[2025-05-22T05:47:16.631+0000] {processor.py:161} INFO - Started process (PID=654) to work on /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:47:16.632+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/(niu)operators.py for tasks to queue
[2025-05-22T05:47:16.634+0000] {logging_mixin.py:188} INFO - [2025-05-22T05:47:16.633+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:47:16.645+0000] {logging_mixin.py:188} INFO - [2025-05-22T05:47:16.644+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/(niu)operators.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/(niu)operators.py", line 32
    Operator (Tasks)
    ^^^^^^^^
IndentationError: expected an indented block after 'with' statement on line 22
[2025-05-22T05:47:16.646+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:47:16.869+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/(niu)operators.py took 0.242 seconds
[2025-05-22T05:47:47.117+0000] {processor.py:161} INFO - Started process (PID=674) to work on /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:47:47.118+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/(niu)operators.py for tasks to queue
[2025-05-22T05:47:47.119+0000] {logging_mixin.py:188} INFO - [2025-05-22T05:47:47.119+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:47:47.131+0000] {logging_mixin.py:188} INFO - [2025-05-22T05:47:47.130+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/(niu)operators.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/(niu)operators.py", line 32
    Operator (Tasks)
    ^^^^^^^^
IndentationError: expected an indented block after 'with' statement on line 22
[2025-05-22T05:47:47.132+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:47:47.357+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/(niu)operators.py took 0.245 seconds
[2025-05-22T05:48:17.725+0000] {processor.py:161} INFO - Started process (PID=698) to work on /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:48:17.726+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/(niu)operators.py for tasks to queue
[2025-05-22T05:48:17.729+0000] {logging_mixin.py:188} INFO - [2025-05-22T05:48:17.728+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:48:17.750+0000] {logging_mixin.py:188} INFO - [2025-05-22T05:48:17.748+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/(niu)operators.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/(niu)operators.py", line 32
    Operator (Tasks)
    ^^^^^^^^
IndentationError: expected an indented block after 'with' statement on line 22
[2025-05-22T05:48:17.750+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:48:18.061+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/(niu)operators.py took 0.354 seconds
[2025-05-22T05:48:48.152+0000] {processor.py:161} INFO - Started process (PID=718) to work on /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:48:48.153+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/(niu)operators.py for tasks to queue
[2025-05-22T05:48:48.155+0000] {logging_mixin.py:188} INFO - [2025-05-22T05:48:48.154+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:48:48.167+0000] {logging_mixin.py:188} INFO - [2025-05-22T05:48:48.166+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/(niu)operators.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/(niu)operators.py", line 32
    Operator (Tasks)
    ^^^^^^^^
IndentationError: expected an indented block after 'with' statement on line 22
[2025-05-22T05:48:48.168+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:48:48.397+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/(niu)operators.py took 0.250 seconds
[2025-05-22T05:49:18.599+0000] {processor.py:161} INFO - Started process (PID=738) to work on /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:49:18.600+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/(niu)operators.py for tasks to queue
[2025-05-22T05:49:18.601+0000] {logging_mixin.py:188} INFO - [2025-05-22T05:49:18.601+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:49:18.615+0000] {logging_mixin.py:188} INFO - [2025-05-22T05:49:18.614+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/(niu)operators.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/(niu)operators.py", line 32
    Operator (Tasks)
    ^^^^^^^^
IndentationError: expected an indented block after 'with' statement on line 22
[2025-05-22T05:49:18.615+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:49:18.797+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/(niu)operators.py took 0.203 seconds
[2025-05-22T05:49:49.122+0000] {processor.py:161} INFO - Started process (PID=758) to work on /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:49:49.123+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/(niu)operators.py for tasks to queue
[2025-05-22T05:49:49.125+0000] {logging_mixin.py:188} INFO - [2025-05-22T05:49:49.124+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:49:49.146+0000] {logging_mixin.py:188} INFO - [2025-05-22T05:49:49.145+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/(niu)operators.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/(niu)operators.py", line 32
    Operator (Tasks)
    ^^^^^^^^
IndentationError: expected an indented block after 'with' statement on line 22
[2025-05-22T05:49:49.147+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:49:49.352+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/(niu)operators.py took 0.235 seconds
[2025-05-22T05:50:19.526+0000] {processor.py:161} INFO - Started process (PID=776) to work on /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:50:19.527+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/(niu)operators.py for tasks to queue
[2025-05-22T05:50:19.528+0000] {logging_mixin.py:188} INFO - [2025-05-22T05:50:19.528+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:50:19.542+0000] {logging_mixin.py:188} INFO - [2025-05-22T05:50:19.541+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/(niu)operators.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/(niu)operators.py", line 32
    Operator (Tasks)
    ^^^^^^^^
IndentationError: expected an indented block after 'with' statement on line 22
[2025-05-22T05:50:19.543+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:50:22.968+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/(niu)operators.py took 3.449 seconds
[2025-05-22T05:50:53.830+0000] {processor.py:161} INFO - Started process (PID=798) to work on /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:50:53.832+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/(niu)operators.py for tasks to queue
[2025-05-22T05:50:53.834+0000] {logging_mixin.py:188} INFO - [2025-05-22T05:50:53.833+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:50:53.856+0000] {logging_mixin.py:188} INFO - [2025-05-22T05:50:53.855+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/(niu)operators.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/(niu)operators.py", line 32
    Operator (Tasks)
    ^^^^^^^^
IndentationError: expected an indented block after 'with' statement on line 22
[2025-05-22T05:50:53.857+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:50:54.065+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/(niu)operators.py took 0.242 seconds
[2025-05-22T05:51:24.164+0000] {processor.py:161} INFO - Started process (PID=818) to work on /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:51:24.165+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/(niu)operators.py for tasks to queue
[2025-05-22T05:51:24.166+0000] {logging_mixin.py:188} INFO - [2025-05-22T05:51:24.166+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:51:24.178+0000] {logging_mixin.py:188} INFO - [2025-05-22T05:51:24.177+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/(niu)operators.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/(niu)operators.py", line 32
    Operator (Tasks)
    ^^^^^^^^
IndentationError: expected an indented block after 'with' statement on line 22
[2025-05-22T05:51:24.179+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:51:24.418+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/(niu)operators.py took 0.259 seconds
[2025-05-22T05:51:54.949+0000] {processor.py:161} INFO - Started process (PID=838) to work on /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:51:54.950+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/(niu)operators.py for tasks to queue
[2025-05-22T05:51:54.952+0000] {logging_mixin.py:188} INFO - [2025-05-22T05:51:54.951+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:51:54.972+0000] {logging_mixin.py:188} INFO - [2025-05-22T05:51:54.971+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/(niu)operators.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/(niu)operators.py", line 32
    Operator (Tasks)
    ^^^^^^^^
IndentationError: expected an indented block after 'with' statement on line 22
[2025-05-22T05:51:54.973+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:51:55.208+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/(niu)operators.py took 0.265 seconds
[2025-05-22T05:52:25.263+0000] {processor.py:161} INFO - Started process (PID=862) to work on /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:52:25.264+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/(niu)operators.py for tasks to queue
[2025-05-22T05:52:25.265+0000] {logging_mixin.py:188} INFO - [2025-05-22T05:52:25.265+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:52:25.276+0000] {logging_mixin.py:188} INFO - [2025-05-22T05:52:25.275+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/(niu)operators.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/(niu)operators.py", line 32
    Operator (Tasks)
    ^^^^^^^^
IndentationError: expected an indented block after 'with' statement on line 22
[2025-05-22T05:52:25.277+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:52:25.548+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/(niu)operators.py took 0.290 seconds
[2025-05-22T05:52:56.345+0000] {processor.py:161} INFO - Started process (PID=882) to work on /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:52:56.346+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/(niu)operators.py for tasks to queue
[2025-05-22T05:52:56.349+0000] {logging_mixin.py:188} INFO - [2025-05-22T05:52:56.348+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:52:56.363+0000] {logging_mixin.py:188} INFO - [2025-05-22T05:52:56.362+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/(niu)operators.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/(niu)operators.py", line 32
    Operator (Tasks)
    ^^^^^^^^
IndentationError: expected an indented block after 'with' statement on line 22
[2025-05-22T05:52:56.364+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:52:56.617+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/(niu)operators.py took 0.280 seconds
[2025-05-22T05:53:27.450+0000] {processor.py:161} INFO - Started process (PID=908) to work on /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:53:27.451+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/(niu)operators.py for tasks to queue
[2025-05-22T05:53:27.453+0000] {logging_mixin.py:188} INFO - [2025-05-22T05:53:27.453+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:53:27.483+0000] {logging_mixin.py:188} INFO - [2025-05-22T05:53:27.482+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/(niu)operators.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/(niu)operators.py", line 32
    Operator (Tasks)
    ^^^^^^^^
IndentationError: expected an indented block after 'with' statement on line 22
[2025-05-22T05:53:27.484+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:53:27.696+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/(niu)operators.py took 0.250 seconds
[2025-05-22T05:53:57.975+0000] {processor.py:161} INFO - Started process (PID=928) to work on /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:53:57.976+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/(niu)operators.py for tasks to queue
[2025-05-22T05:53:57.978+0000] {logging_mixin.py:188} INFO - [2025-05-22T05:53:57.978+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:53:58.020+0000] {logging_mixin.py:188} INFO - [2025-05-22T05:53:58.019+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/(niu)operators.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/(niu)operators.py", line 32
    Operator (Tasks)
    ^^^^^^^^
IndentationError: expected an indented block after 'with' statement on line 22
[2025-05-22T05:53:58.021+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:53:58.304+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/(niu)operators.py took 0.340 seconds
[2025-05-22T05:54:28.691+0000] {processor.py:161} INFO - Started process (PID=954) to work on /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:54:28.692+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/(niu)operators.py for tasks to queue
[2025-05-22T05:54:28.693+0000] {logging_mixin.py:188} INFO - [2025-05-22T05:54:28.693+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:54:28.705+0000] {logging_mixin.py:188} INFO - [2025-05-22T05:54:28.704+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/(niu)operators.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/(niu)operators.py", line 32
    Operator (Tasks)
    ^^^^^^^^
IndentationError: expected an indented block after 'with' statement on line 22
[2025-05-22T05:54:28.706+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:54:29.316+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/(niu)operators.py took 0.631 seconds
[2025-05-22T05:55:00.172+0000] {processor.py:161} INFO - Started process (PID=980) to work on /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:55:00.173+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/(niu)operators.py for tasks to queue
[2025-05-22T05:55:00.175+0000] {logging_mixin.py:188} INFO - [2025-05-22T05:55:00.174+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:55:00.190+0000] {logging_mixin.py:188} INFO - [2025-05-22T05:55:00.188+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/(niu)operators.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/(niu)operators.py", line 32
    Operator (Tasks)
    ^^^^^^^^
IndentationError: expected an indented block after 'with' statement on line 22
[2025-05-22T05:55:00.191+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:55:00.535+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/(niu)operators.py took 0.369 seconds
[2025-05-22T05:55:30.690+0000] {processor.py:161} INFO - Started process (PID=1004) to work on /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:55:30.691+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/(niu)operators.py for tasks to queue
[2025-05-22T05:55:30.693+0000] {logging_mixin.py:188} INFO - [2025-05-22T05:55:30.693+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:55:30.703+0000] {logging_mixin.py:188} INFO - [2025-05-22T05:55:30.702+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/(niu)operators.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/(niu)operators.py", line 32
    Operator (Tasks)
    ^^^^^^^^
IndentationError: expected an indented block after 'with' statement on line 22
[2025-05-22T05:55:30.704+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:55:30.964+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/(niu)operators.py took 0.279 seconds
[2025-05-22T05:56:01.416+0000] {processor.py:161} INFO - Started process (PID=1024) to work on /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:56:01.417+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/(niu)operators.py for tasks to queue
[2025-05-22T05:56:01.417+0000] {logging_mixin.py:188} INFO - [2025-05-22T05:56:01.417+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:56:01.429+0000] {logging_mixin.py:188} INFO - [2025-05-22T05:56:01.428+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/(niu)operators.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/(niu)operators.py", line 32
    Operator (Tasks)
    ^^^^^^^^
IndentationError: expected an indented block after 'with' statement on line 22
[2025-05-22T05:56:01.430+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/(niu)operators.py
[2025-05-22T05:56:01.641+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/(niu)operators.py took 0.231 seconds
