[2025-06-03T03:26:32.101+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-06-03T03:26:32.316+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: random_user_pipeline.wait_for_existing_data manual__2025-06-03T03:26:25.484907+00:00 [queued]>
[2025-06-03T03:26:32.327+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: random_user_pipeline.wait_for_existing_data manual__2025-06-03T03:26:25.484907+00:00 [queued]>
[2025-06-03T03:26:32.329+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-06-03T03:26:32.348+0000] {taskinstance.py:2330} INFO - Executing <Task(SqlSensor): wait_for_existing_data> on 2025-06-03 03:26:25.484907+00:00
[2025-06-03T03:26:32.354+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=221) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-06-03T03:26:32.355+0000] {standard_task_runner.py:63} INFO - Started process 222 to run task
[2025-06-03T03:26:32.354+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'random_user_pipeline', 'wait_for_existing_data', 'manual__2025-06-03T03:26:25.484907+00:00', '--job-id', '456', '--raw', '--subdir', 'DAGS_FOLDER/random_user_pipeline.py', '--cfg-path', '/tmp/tmpcu0z2ijh']
[2025-06-03T03:26:32.356+0000] {standard_task_runner.py:91} INFO - Job 456: Subtask wait_for_existing_data
[2025-06-03T03:26:32.969+0000] {task_command.py:426} INFO - Running <TaskInstance: random_user_pipeline.wait_for_existing_data manual__2025-06-03T03:26:25.484907+00:00 [running]> on host 87db888b1009
[2025-06-03T03:26:33.857+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='papala.ramesh@quation.in,smilesoframs@gmail.com' AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='random_user_pipeline' AIRFLOW_CTX_TASK_ID='wait_for_existing_data' AIRFLOW_CTX_EXECUTION_DATE='2025-06-03T03:26:25.484907+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-03T03:26:25.484907+00:00'
[2025-06-03T03:26:33.858+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-06-03T03:26:33.872+0000] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2025-06-03T03:26:33.873+0000] {base.py:84} INFO - Using connection ID '***_default' for task execution.
[2025-06-03T03:26:33.875+0000] {sql.py:95} INFO - Poking: SELECT 1 FROM products WHERE DATE(created_at) = CURRENT_DATE LIMIT 1; (with parameters None)
[2025-06-03T03:26:33.876+0000] {base.py:84} INFO - Using connection ID '***_default' for task execution.
[2025-06-03T03:26:34.152+0000] {sql.py:487} INFO - Running statement: SELECT 1 FROM products WHERE DATE(created_at) = CURRENT_DATE LIMIT 1;, parameters: None
[2025-06-03T03:26:34.156+0000] {sql.py:496} INFO - Rows affected: 0
[2025-06-03T03:27:04.156+0000] {base.py:84} INFO - Using connection ID '***_default' for task execution.
[2025-06-03T03:27:04.157+0000] {sql.py:95} INFO - Poking: SELECT 1 FROM products WHERE DATE(created_at) = CURRENT_DATE LIMIT 1; (with parameters None)
[2025-06-03T03:27:04.158+0000] {base.py:84} INFO - Using connection ID '***_default' for task execution.
[2025-06-03T03:27:04.378+0000] {sql.py:487} INFO - Running statement: SELECT 1 FROM products WHERE DATE(created_at) = CURRENT_DATE LIMIT 1;, parameters: None
[2025-06-03T03:27:04.381+0000] {sql.py:496} INFO - Rows affected: 0
[2025-06-03T03:27:34.381+0000] {base.py:84} INFO - Using connection ID '***_default' for task execution.
[2025-06-03T03:27:34.382+0000] {sql.py:95} INFO - Poking: SELECT 1 FROM products WHERE DATE(created_at) = CURRENT_DATE LIMIT 1; (with parameters None)
[2025-06-03T03:27:34.383+0000] {base.py:84} INFO - Using connection ID '***_default' for task execution.
[2025-06-03T03:27:38.395+0000] {sql.py:487} INFO - Running statement: SELECT 1 FROM products WHERE DATE(created_at) = CURRENT_DATE LIMIT 1;, parameters: None
[2025-06-03T03:27:38.398+0000] {sql.py:496} INFO - Rows affected: 0
[2025-06-03T03:28:08.399+0000] {base.py:84} INFO - Using connection ID '***_default' for task execution.
[2025-06-03T03:28:08.401+0000] {sql.py:95} INFO - Poking: SELECT 1 FROM products WHERE DATE(created_at) = CURRENT_DATE LIMIT 1; (with parameters None)
[2025-06-03T03:28:08.403+0000] {base.py:84} INFO - Using connection ID '***_default' for task execution.
[2025-06-03T03:28:08.639+0000] {sql.py:487} INFO - Running statement: SELECT 1 FROM products WHERE DATE(created_at) = CURRENT_DATE LIMIT 1;, parameters: None
[2025-06-03T03:28:08.642+0000] {sql.py:496} INFO - Rows affected: 0
[2025-06-03T03:28:38.643+0000] {base.py:84} INFO - Using connection ID '***_default' for task execution.
[2025-06-03T03:28:38.644+0000] {sql.py:95} INFO - Poking: SELECT 1 FROM products WHERE DATE(created_at) = CURRENT_DATE LIMIT 1; (with parameters None)
[2025-06-03T03:28:38.645+0000] {base.py:84} INFO - Using connection ID '***_default' for task execution.
[2025-06-03T03:28:38.845+0000] {sql.py:487} INFO - Running statement: SELECT 1 FROM products WHERE DATE(created_at) = CURRENT_DATE LIMIT 1;, parameters: None
[2025-06-03T03:28:38.850+0000] {sql.py:496} INFO - Rows affected: 0
[2025-06-03T03:28:38.852+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-06-03T03:28:38.852+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/sensors/base.py", line 281, in execute
    raise AirflowSensorTimeout(message)
airflow.exceptions.AirflowSensorTimeout: Sensor has timed out; run duration of 124.98651646900001 seconds exceeds the specified timeout of 120.0.
[2025-06-03T03:28:41.136+0000] {taskinstance.py:1206} INFO - Immediate failure requested. Marking task as FAILED. dag_id=random_user_pipeline, task_id=wait_for_existing_data, run_id=manual__2025-06-03T03:26:25.484907+00:00, execution_date=20250603T032625, start_date=20250603T032632, end_date=20250603T032841
[2025-06-03T03:28:41.154+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/utils/email.py:154 RemovedInAirflow3Warning: Fetching SMTP credentials from configuration variables will be deprecated in a future release. Please set credentials using a connection instead.
[2025-06-03T03:28:41.155+0000] {email.py:271} INFO - Email alerting: attempt 1
[2025-06-03T03:28:42.432+0000] {email.py:282} INFO - Sent an alert email to ['papala.ramesh@quation.in', 'smilesoframs@gmail.com']
[2025-06-03T03:28:44.726+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 456 for task wait_for_existing_data (Sensor has timed out; run duration of 124.98651646900001 seconds exceeds the specified timeout of 120.0.; 222)
[2025-06-03T03:28:44.739+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-06-03T03:28:45.054+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py:1297 AirflowProviderDeprecationWarning: Call to deprecated class PostgresOperator. (Please use `airflow.providers.common.sql.operators.sql.SQLExecuteQueryOperator`.Also, you can provide `hook_params={'schema': <database>}`.)
[2025-06-03T03:28:45.128+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-06-03T03:28:45.139+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
